const obce =   [
  'Ábelová',
  'Abovce',
  'Abrahám',
  'Abrahámovce',
  'Abrahámovce',
  'Abramová',
  'Abranovce',
  'Adamovské Kochanovce',
  'Adidovce',
  'Alekšince',
  'Andovce',
  'Andrejová',
  'Ardanovce',
  'Ardovo',
  'Arnutovce',
  'Báb',
  'Babie',
  'Babín',
  'Babiná',
  'Babindol',
  'Babinec',
  'Bacúch',
  'Bacúrov',
  'Báč',
  'Bačka',
  'Bačkov',
  'Bačkovík',
  'Baďan',
  'Bádice',
  'Badín',
  'Báhoň',
  'Bajany',
  'Bajč',
  'Bajerov',
  'Bajerovce',
  'Bajka',
  'Bajtava',
  'Baka',
  'Baláže',
  'Baldovce',
  'Balog nad Ipľom',
  'Baloň',
  'Baňa',
  'Banka',
  'Bánov',
  'Bánovce nad Bebravou',
  'Bánovce nad Ondavou',
  'Banská Belá',
  'Banská Bystrica',
  'Banská Štiavnica',
  'Banské',
  'Banský Studenec',
  'Bara',
  'Barca',
  'Bardejov',
  'Bardoňovo',
  'Bartošova Lehôtka',
  'Bartošovce',
  'Baška',
  'Baškovce',
  'Baškovce',
  'Bašovce',
  'Batizovce',
  'Bátka',
  'Bátorová',
  'Bátorove Kosihy',
  'Bátovce',
  'Beckov',
  'Beharovce',
  'Becherov',
  'Belá',
  'Belá',
  'Belá - Dulice',
  'Belá nad Cirochou',
  'Beladice',
  'Belejovce',
  'Belín',
  'Belina',
  'Belince',
  'Bellova Ves',
  'Beloveža',
  'Beluj',
  'Beluša',
  'Belža',
  'Beňadiková',
  'Beňadikovce',
  'Beňadovo',
  'Beňatina',
  'Beniakovce',
  'Benice',
  'Benkovce',
  'Beňuš',
  'Bernolákovo',
  'Bertotovce',
  'Beša',
  'Beša',
  'Bešeňov',
  'Bešeňová',
  'Betlanovce',
  'Betliar',
  'Bežovce',
  'Bidovce',
  'Biel',
  'Bielovce',
  'Biely Kostol',
  'Bijacovce',
  'Bílkove Humence',
  'Bíňa',
  'Bíňovce',
  'Biskupice',
  'Biskupová',
  'Bitarová',
  'Blahová',
  'Blatná na Ostrove',
  'Blatná Polianka',
  'Blatné',
  'Blatné Remety',
  'Blatné Revištia',
  'Blatnica',
  'Blažice',
  'Blažovce',
  'Blhovce',
  'Bobot',
  'Bobrov',
  'Bobrovček',
  'Bobrovec',
  'Bobrovník',
  'Bočiar',
  'Bodíky',
  'Bodiná',
  'Bodorová',
  'Bodovce',
  'Bodružal',
  'Bodza',
  'Bodzianske Lúky',
  'Bogliarka',
  'Bohdanovce',
  'Bohdanovce nad Trnavou',
  'Boheľov',
  'Bohunice',
  'Bohunice',
  'Bohúňovo',
  'Bojná',
  'Bojnice',
  'Bojničky',
  'Boľ',
  'Boldog',
  'Boleráz',
  'Bolešov',
  'Boliarov',
  'Boľkovce',
  'Borcová',
  'Borčany',
  'Borčice',
  'Borinka',
  'Borová',
  'Borovce',
  'Borský Mikuláš',
  'Borský Svätý Jur',
  'Borša',
  'Bory',
  'Bošáca',
  'Bošany',
  'Boťany',
  'Bottovo',
  'Bôrka',
  'Bracovce',
  'Branč',
  'Branovo',
  'Bratislava',
  'Bratislava - mestská časť Čunovo',
  'Bratislava – mestská časť Devín',
  'Bratislava - mestská časť Devínska Nová Ves',
  'Bratislava – mestská časť Dúbravka',
  'Bratislava – mestská časť Jarovce',
  'Bratislava - mestská časť Karlova Ves',
  'Bratislava - mestská časť Lamač',
  'Bratislava – mestská časť Nové Mesto',
  'Bratislava - mestská časť Petržalka',
  'Bratislava - mestská časť Podunajské Biskupice',
  'Bratislava - mestská časť Rača',
  'Bratislava - mestská časť Rusovce',
  'Bratislava – mestská časť Ružinov',
  'Bratislava – mestská časť Staré Mesto',
  'Bratislava – mestská časť Vajnory',
  'Bratislava – mestská časť Vrakuňa',
  'Bratislava – mestská časť Záhorská Bystrica',
  'Braväcovo',
  'Brdárka',
  'Brehov',
  'Brehy',
  'Brekov',
  'Brestov',
  'Brestov',
  'Brestov nad Laborcom',
  'Brestovany',
  'Brestovec',
  'Brestovec',
  'Bretejovce',
  'Bretka',
  'Breza',
  'Brezany',
  'Brezina',
  'Breziny',
  'Breznica',
  'Breznička (okres Poltár)',
  'Breznička (okres Stropkov)',
  'Brezno',
  'Brezolupy',
  'Brezov',
  'Brezová pod Bradlom',
  'Brezovec',
  'Brezovica',
  'Brezovica',
  'Brezovička',
  'Brezovka',
  'Brežany',
  'Brhlovce',
  'Brieštie',
  'Brodské',
  'Brodzany',
  'Brunovce',
  'Brusnica',
  'Brusník',
  'Brusno',
  'Brutovce',
  'Bruty',
  'Brvnište',
  'Brzotín',
  'Buclovany',
  'Búč',
  'Bučany',
  'Budča',
  'Budikovany',
  'Budimír',
  'Budiná',
  'Budince',
  'Budiš',
  'Budkovce',
  'Budmerice',
  'Buglovce',
  'Buková',
  'Bukovce',
  'Bukovec',
  'Bukovec',
  'Bukovina',
  'Bulhary',
  'Bunetice',
  'Bunkovce',
  'Bušince',
  'Bušovce',
  'Buzica',
  'Buzitka',
  'Bystrá',
  'Bystrá',
  'Bystrany',
  'Bystré',
  'Bystričany',
  'Bystrička',
  'Byšta',
  'Bytča',
  'Bzenica',
  'Bzenov',
  'Bzince pod Javorinou',
  'Bziny',
  'Bzovík',
  'Bzovská Lehôtka',
  'Bžany',
  'Cabaj-Čápor',
  'Cabov',
  'Cakov',
  'Cejkov',
  'Cernina',
  'Cerová',
  'Cerovo',
  'Cestice',
  'Cífer',
  'Cigeľ',
  'Cigeľka',
  'Cigla',
  'Cimenná',
  'Cinobaňa',
  'Čab',
  'Čabalovce',
  'Čabiny',
  'Čabradský Vrbovok',
  'Čadca',
  'Čachtice',
  'Čajkov',
  'Čaka',
  'Čakajovce',
  'Čakanovce',
  'Čakanovce',
  'Čakany',
  'Čaklov',
  'Čalovec',
  'Čamovce',
  'Čaňa',
  'Čaradice',
  'Čáry',
  'Častá',
  'Častkov',
  'Častkovce',
  'Čata',
  'Čataj',
  'Čavoj',
  'Čebovce',
  'Čečehov',
  'Čečejovce',
  'Čechy',
  'Čechynce',
  'Čekovce',
  'Čeľadice',
  'Čeľadince',
  'Čeláre',
  'Čelkova Lehota',
  'Čelovce',
  'Čelovce',
  'Čeľovce',
  'Čenkovce',
  'Čereňany',
  'Čerenčany',
  'Čerhov',
  'Čerín',
  'Čermany',
  'Černík',
  'Černina',
  'Černochov',
  'Čertižné',
  'Červená Voda',
  'Červeňany',
  'Červenica',
  'Červenica pri Sabinove',
  'Červeník',
  'Červený Hrádok',
  'Červený Kameň',
  'Červený Kláštor',
  'České Brezovo',
  'Čičarovce',
  'Čičava',
  'Čičmany',
  'Číčov',
  'Čierna',
  'Čierna Lehota',
  'Čierna Lehota',
  'Čierna nad Tisou',
  'Čierna Voda',
  'Čierne',
  'Čierne Kľačany',
  'Čierne nad Topľou',
  'Čierne Pole',
  'Čierny Balog',
  'Čierny Potok',
  'Čifáre',
  'Čiližská Radvaň',
  'Čimhová',
  'Čirč',
  'Číž',
  'Čižatice',
  'Čoltovo',
  'Čremošné',
  'Čučma',
  'Čukalovce',
  'Ďačov',
  'Dačov Lom',
  'Daletice',
  'Danišovce',
  'Ďanová',
  'Ďapalovce',
  'Dargov',
  'Davidov',
  'Debraď',
  'Dedačov',
  'Dedina Mládeže',
  'Dedinka',
  'Dedinky',
  'Dechtice',
  'Dekýš',
  'Demandice',
  'Demänovská Dolina',
  'Demjata',
  'Detrík',
  'Detva',
  'Detvianska Huta',
  'Devičany',
  'Devičie',
  'Dežerice',
  'Diaková',
  'Diakovce',
  'Diviacka Nová Ves',
  'Diviaky nad Nitricou',
  'Divín',
  'Divina',
  'Divinka',
  'Dlhá',
  'Dlhá nad Kysucou',
  'Dlhá nad Oravou',
  'Dlhá nad Váhom',
  'Dlhá Ves',
  'Dlhé Klčovo',
  'Dlhé nad Cirochou',
  'Dlhé Pole',
  'Dlhé Stráže',
  'Dlhoňa',
  'Dlžín',
  'Dobrá',
  'Dobrá Niva',
  'Dobrá Voda',
  'Dobroč',
  'Dobrohošť',
  'Dobroslava',
  'Dobšiná',
  'Dohňany',
  'Dojč',
  'Doľany',
  'Doľany',
  'Dolinka',
  'Dolná Breznica',
  'Dolná Krupá',
  'Dolná Lehota',
  'Dolná Mariková',
  'Dolná Mičiná',
  'Dolná Poruba',
  'Dolná Seč',
  'Dolná Streda',
  'Dolná Strehová',
  'Dolná Súča',
  'Dolná Tižina',
  'Dolná Trnávka',
  'Dolná Ves',
  'Dolná Ždaňa',
  'Dolné Dubové',
  'Dolné Kočkovce',
  'Dolné Lefantovce',
  'Dolné Lovčice',
  'Dolné Mladonice',
  'Dolné Naštice',
  'Dolné Obdokovce',
  'Dolné Orešany',
  'Dolné Otrokovce',
  'Dolné Plachtince',
  'Dolné Saliby',
  'Dolné Semerovce',
  'Dolné Srnie',
  'Dolné Strháre',
  'Dolné Trhovište',
  'Dolné Vestenice',
  'Dolné Zahorany',
  'Dolné Zelenice',
  'Dolný Badín',
  'Dolný Bar',
  'Dolný Hričov',
  'Dolný Chotár',
  'Dolný Kalník',
  'Dolný Kubín',
  'Dolný Lieskov',
  'Dolný Lopašov',
  'Dolný Ohaj',
  'Dolný Pial',
  'Dolný Štál',
  'Dolný Vadičov',
  'Domadice',
  'Domaníky',
  'Domaniža',
  'Domaňovce',
  'Donovaly',
  'Drábsko',
  'Drahňov',
  'Drahovce',
  'Dravce',
  'Dražice',
  'Dražkovce',
  'Drážovce',
  'Drienčany',
  'Drienica',
  'Drienov',
  'Drienovec',
  'Drienovo',
  'Drienovská Nová Ves',
  'Drietoma',
  'Drňa',
  'Drnava',
  'Družstevná pri Hornáde',
  'Drženice',
  'Držkovce',
  'Ďubákovo',
  'Dubinné',
  'Dubnica nad Váhom',
  'Dubnička',
  'Dubník',
  'Dubodiel',
  'Dubová',
  'Dubová',
  'Dubovany',
  'Dubovce',
  'Dubové',
  'Dubové',
  'Dubovec',
  'Dubovica',
  'Dúbrava',
  'Dúbrava',
  'Dúbrava',
  'Dúbravica',
  'Dúbravka',
  'Dúbravy',
  'Ducové',
  'Dudince',
  'Dukovce',
  'Dulov',
  'Dulova Ves',
  'Dulovce',
  'Dulovo',
  'Dunajov',
  'Dunajská Lužná',
  'Dunajská Streda',
  'Dunajský Klátov',
  'Duplín',
  'Ďurčiná',
  'Ďurďoš',
  'Ďurďošík',
  'Ďurďové',
  'Ďurkov',
  'Ďurková',
  'Ďurkovce',
  'Dvorany nad Nitrou',
  'Dvorec',
  'Dvorianky',
  'Dvorníky',
  'Dvorníky - Včeláre',
  'Dvory nad Žitavou',
  'Egreš',
  'Fačkov',
  'Falkušovce',
  'Farná',
  'Fekišovce',
  'Figa',
  'Fijaš',
  'Fiľakovo',
  'Fiľakovské Kováče',
  'Fintice',
  'Folkušová',
  'Forbasy',
  'Frička',
  'Fričkovce',
  'Fričovce',
  'Fulianka',
  'Gabčíkovo',
  'Gaboltov',
  'Gajary',
  'Galanta',
  'Galovany',
  'Gáň',
  'Gánovce',
  'Gbeľany',
  'Gbelce',
  'Gbely',
  'Geča',
  'Gelnica',
  'Gemer',
  'Gemerček',
  'Gemerská Hôrka',
  'Gemerská Panica',
  'Gemerská Poloma',
  'Gemerská Ves',
  'Gemerské Dechtáre',
  'Gemerské Michalovce',
  'Gemerské Teplice',
  'Gemerský Jablonec',
  'Gemerský Sad',
  'Geraltov',
  'Gerlachov',
  'Gerlachov',
  'Giglovce',
  'Giraltovce',
  'Glabušovce',
  'Gočaltovo',
  'Gočovo',
  'Golianovo',
  'Gortva',
  'Gôtovany',
  'Granč - Petrovce',
  'Gregorova Vieska',
  'Gregorovce',
  'Gribov',
  'Gruzovce',
  'Gyňov',
  'Habovka',
  'Habura',
  'Hačava',
  'Háj',
  'Háj',
  'Hajná Nová Ves',
  'Hajnáčka',
  'Hájske',
  'Hajtovka',
  'Haláčovce',
  'Halič',
  'Haligovce',
  'Haluzice',
  'Hamuliakovo',
  'Handlová',
  'Hanigovce',
  'Haniska',
  'Haniska',
  'Hanková',
  'Hankovce',
  'Hankovce',
  'Hanušovce nad Topľou',
  'Harakovce',
  'Harhaj',
  'Harichovce',
  'Harmanec',
  'Hatalov',
  'Hatné',
  'Havaj',
  'Havka',
  'Havranec',
  'Hažín',
  'Hažín nad Cirochou',
  'Hažlín',
  'Helcmanovce',
  'Heľpa',
  'Henckovce',
  'Henclová',
  'Hencovce',
  'Hendrichovce',
  'Herľany',
  'Hermanovce',
  'Hermanovce nad Topľou',
  'Hertník',
  'Hervartov',
  'Hiadeľ',
  'Hincovce',
  'Hladovka',
  'Hlboké',
  'Hlboké nad Váhom',
  'Hliník nad Hronom',
  'Hlinné',
  'Hlivištia',
  'Hlohovec',
  'Hniezdne',
  'Hnilčík',
  'Hnilec',
  'Hnojné',
  'Hnúšťa',
  'Hodejov',
  'Hodejovec',
  'Hodkovce',
  'Hodruša - Hámre',
  'Hokovce',
  'Holčíkovce',
  'Holiare',
  'Holice',
  'Holíč',
  'Holiša',
  'Holumnica',
  'Honce',
  'Hontianska Vrbica',
  'Hontianske Moravce',
  'Hontianske Nemce',
  'Hontianske Tesáre',
  'Hontianske Trsťany',
  'Horňa',
  'Horná Breznica',
  'Horná Kráľová',
  'Horná Krupá',
  'Horná Lehota',
  'Horná Mariková',
  'Horná Mičiná',
  'Horná Poruba',
  'Horná Potôň',
  'Horná Seč',
  'Horná Streda',
  'Horná Strehová',
  'Horná Súča',
  'Horná Štubňa',
  'Horná Ves',
  'Horná Ves',
  'Horná Ždaňa',
  'Horňany',
  'Horné Dubové',
  'Horné Hámre',
  'Horné Chlebany',
  'Horné Lefantovce',
  'Horné Mladonice',
  'Horné Mýto',
  'Horné Naštice',
  'Horné Obdokovce',
  'Horné Orešany',
  'Horné Otrokovce',
  'Horné Plachtince',
  'Horné Pršany',
  'Horné Saliby',
  'Horné Semerovce',
  'Horné Srnie',
  'Horné Strháre',
  'Horné Štitáre',
  'Horné Trhovište',
  'Horné Turovce',
  'Horné Vestenice',
  'Horné Zahorany',
  'Horné Zelenice',
  'Horný Badín',
  'Horný Bar',
  'Horný Hričov',
  'Horný Kalník',
  'Horný Lieskov',
  'Horný Pial',
  'Horný Tisovník',
  'Horný Vadičov',
  'Horovce',
  'Horovce',
  'Hoste',
  'Hostice',
  'Hostie',
  'Hostišovce',
  'Hosťová',
  'Hosťovce',
  'Hosťovce',
  'Hostovice',
  'Hozelec',
  'Hôrka',
  'Hôrka nad Váhom',
  'Hôrky',
  'Hrabičov',
  'Hrabkov',
  'Hrabová Roztoka',
  'Hrabovčík',
  'Hrabovec',
  'Hrabovec nad Laborcom',
  'Hrabovka',
  'Hrabské',
  'Hrabušice',
  'Hradisko',
  'Hradište',
  'Hradište',
  'Hradište pod Vrátnom',
  'Hrádok',
  'Hrachovište',
  'Hrachovo',
  'Hraň',
  'Hraničné',
  'Hranovnica',
  'Hrašné',
  'Hrašovík',
  'Hrčeľ',
  'Hrhov',
  'Hriadky',
  'Hričovské Podhradie',
  'Hriňová',
  'Hrišovce',
  'Hrkovce',
  'Hrlica',
  'Hrnčiarovce nad Parnou',
  'Hrnčiarska Ves',
  'Hrnčiarske Zalužany',
  'Hrochoť',
  'Hromoš',
  'Hronec',
  'Hronovce',
  'Hronsek',
  'Hronská Breznica',
  'Hronská Dúbrava',
  'Hronské Kľačany',
  'Hronské Kosihy',
  'Hronský Beňadik',
  'Hrubá Borša',
  'Hruboňovo',
  'Hrubov',
  'Hrubý Šúr',
  'Hrušov',
  'Hrušov',
  'Hrušovany',
  'Hrušovo',
  'Hruštín',
  'Hubice',
  'Hubina',
  'Hubošovce',
  'Hubová',
  'Hubovo',
  'Hucín',
  'Hudcovce',
  'Hul',
  'Humenné',
  'Huncovce',
  'Hunkovce',
  'Hurbanova Ves',
  'Hurbanovo',
  'Husák',
  'Husiná',
  'Hutka',
  'Huty',
  'Hviezdoslavov',
  'Hvozdnica',
  'Hybe',
  'Hýľov',
  'Chanava',
  'Chľaba',
  'Chlebnice',
  'Chlmec',
  'Chmeľnica',
  'Chmeľov',
  'Chmeľová',
  'Chmeľovec',
  'Chmiňany',
  'Chminianska Nová Ves',
  'Chminianske Jakubovany',
  'Choča',
  'Chocholná - Velčice',
  'Choňkovce',
  'Chorvátsky Grob',
  'Chorváty',
  'Chotča',
  'Chotín',
  'Chrabrany',
  'Chrámec',
  'Chrasť nad Hornádom',
  'Chrastince',
  'Chrastné',
  'Chrenovec - Brusno',
  'Chropov',
  'Chrťany',
  'Chtelnica',
  'Chudá Lehota',
  'Chvalová',
  'Chvojnica',
  'Chvojnica',
  'Chynorany',
  'Chyžné',
  'Igram',
  'Ihľany',
  'Ihráč',
  'Ilava',
  'Iliašovce',
  'Ilija',
  'Imeľ',
  'Iňa',
  'Iňačovce',
  'Inovce',
  'Ipeľské Predmostie',
  'Ipeľské Úľany',
  'Ipeľský Sokolec',
  'Istebné',
  'Ivachnová',
  'Ivančiná',
  'Ivanice',
  'Ivanka pri Dunaji',
  'Ivanka pri Nitre',
  'Ivanovce',
  'Iža',
  'Ižipovce',
  'Ižkovce',
  'Jabloň',
  'Jablonec',
  'Jablonica',
  'Jablonka',
  'Jablonov',
  'Jablonov nad Turňou',
  'Jabloňovce',
  'Jablonové',
  'Jablonové',
  'Jacovce',
  'Jahodná',
  'Jaklovce',
  'Jakovany',
  'Jakubany',
  'Jakubov',
  'Jakubova Voľa',
  'Jakubovany',
  'Jakubovany',
  'Jakušovce',
  'Jalová',
  'Jalovec',
  'Jalšové',
  'Jalšovík',
  'Jamník',
  'Jamník',
  'Janice',
  'Janík',
  'Janíky',
  'Jankovce',
  'Janov',
  'Janova Lehota',
  'Janovce',
  'Jánovce',
  'Jánovce',
  'Janovík',
  'Jarabá',
  'Jarabina',
  'Jarok',
  'Jarovnice',
  'Jasenica',
  'Jasenie',
  'Jasenov',
  'Jasenov',
  'Jasenová',
  'Jasenovce',
  'Jasenové',
  'Jasenovo',
  'Jaslovské Bohunice',
  'Jasov',
  'Jasová',
  'Jastrabá',
  'Jastrabie nad Topľou',
  'Jastrabie pri Michalovciach',
  'Jatov',
  'Jazernica',
  'Jedlinka',
  'Jedľové Kostoľany',
  'Jelenec',
  'Jelka',
  'Jelšava',
  'Jelšovce',
  'Jelšovec',
  'Jenkovce',
  'Jesenské',
  'Jesenské',
  'Jestice',
  'Ješkova Ves',
  'Jezersko',
  'Jovice',
  'Jovsa',
  'Jur nad Hronom',
  'Jurová',
  'Jurské',
  'Juskova Voľa',
  'Kačanov',
  'Kajal',
  'Kaľamenová',
  'Kalameny',
  'Kaľava',
  'Kalinkovo',
  'Kalinov',
  'Kalinovo',
  'Kalná nad Hronom',
  'Kalná Roztoka',
  'Kálnica',
  'Kalnište',
  'Kalonda',
  'Kaloša',
  'Kalša',
  'Kaluža',
  'Kamanová',
  'Kameňany',
  'Kamenec pod Vtáčnikom',
  'Kamenica',
  'Kamenica nad Cirochou',
  'Kamenica nad Hronom',
  'Kameničany',
  'Kameničná',
  'Kamenín',
  'Kamenná Poruba',
  'Kamenná Poruba',
  'Kamenné Kosihy',
  'Kamenný Most',
  'Kamienka',
  'Kamienka',
  'Kanianka',
  'Kapince',
  'Kapišová',
  'Kaplna',
  'Kapušany',
  'Kapušianske Kľačany',
  'Karlová',
  'Karná',
  'Kašov',
  'Kátlovce',
  'Kátov',
  'Kazimír',
  'Kecerovce',
  'Kecerovský Lipovec',
  'Kečkovce',
  'Kečovo',
  'Kechnec',
  'Kendice',
  'Kesovce',
  'Keť',
  'Kežmarok',
  'Kiarov',
  'Kľačany',
  'Kľače',
  'Kľačno',
  'Kladzany',
  'Kľak',
  'Klasov',
  'Kláštor pod Znievom',
  'Klátova Nová Ves',
  'Klčov',
  'Kleňany',
  'Klenov',
  'Klenová',
  'Klenovec',
  'Klieština',
  'Klin',
  'Klin nad Bodrogom',
  'Klížska Nemá',
  'Klokoč',
  'Klokočov',
  'Klokočov',
  'Klubina',
  'Kľúčovec',
  'Kluknava',
  'Kľušov',
  'Kmeťovo',
  'Kobeliarovo',
  'Kobylnice',
  'Kobyly',
  'Koceľovce',
  'Kociha',
  'Kocurany',
  'Kočín - Lančár',
  'Kočovce',
  'Kochanovce',
  'Kochanovce',
  'Kojatice',
  'Kojšov',
  'Kokava nad Rimavicou',
  'Kokošovce',
  'Kokšov - Bakša',
  'Kolačkov',
  'Kolačno',
  'Koláre',
  'Kolárovice',
  'Kolárovo',
  'Kolbasov',
  'Kolbovce',
  'Kolibabovce',
  'Kolíňany',
  'Kolinovce',
  'Kolonica',
  'Kolta',
  'Komárany',
  'Komárno',
  'Komárov',
  'Komárovce',
  'Komjatice',
  'Komjatná',
  'Komoča',
  'Koniarovce',
  'Konrádovce',
  'Konská',
  'Konská',
  'Koňuš',
  'Kopčany',
  'Kopernica',
  'Koplotovce',
  'Koprivnica',
  'Kordíky',
  'Korejovce',
  'Korňa',
  'Koromľa',
  'Korunková',
  'Korytárky',
  'Korytné',
  'Kosihovce',
  'Kosihy nad Ipľom',
  'Kosorín',
  'Kostoľany nad Hornádom',
  'Kostoľany pod Tribečom',
  'Kostolec',
  'Kostolište',
  'Kostolná - Záriečie',
  'Kostolná pri Dunaji',
  'Kostolná Ves',
  'Kostolné',
  'Kostolné Kračany',
  'Koš',
  'Košariská',
  'Košarovce',
  'Košeca',
  'Košecké Podhradie',
  'Košice',
  'Košice - Barca',
  'Košice - Dargovských hrdinov',
  'Košice - Džungľa',
  'Košice - Juh',
  'Košice - Kavečany',
  'Košice - Košická Nová Ves',
  'Košice - Krásna',
  'Košice - Lorinčík',
  'Košice - Luník IX',
  'Košice - Myslava',
  'Košice - Nad jazerom',
  'Košice - Pereš',
  'Košice - Poľov',
  'Košice - Sever',
  'Košice - Sídlisko KVP',
  'Košice - Sídlisko Ťahanovce',
  'Košice - Staré Mesto',
  'Košice - Šaca',
  'Košice - Šebastovce',
  'Košice - Ťahanovce',
  'Košice - Vyšné Opátske',
  'Košice - Západ',
  'Košická Belá',
  'Košická Polianka',
  'Košické Oľšany',
  'Košický Klečenov',
  'Koškovce',
  'Košolná',
  'Košťany nad Turcom',
  'Košúty',
  'Kotešová',
  'Kotmanová',
  'Kotrčiná Lúčka',
  'Kováčová',
  'Kováčová',
  'Kováčovce',
  'Koválov',
  'Koválovec',
  'Kovarce',
  'Kozárovce',
  'Kozelník',
  'Kozí Vrbovok',
  'Kožany',
  'Kožuchov',
  'Kožuchovce',
  'Kračúnovce',
  'Krahule',
  'Krajná Bystrá',
  'Krajná Poľana',
  'Krajná Porúbka',
  'Krajné',
  'Krajné Čierno',
  'Krakovany',
  'Kráľ',
  'Králiky',
  'Kráľov Brod',
  'Kráľova Lehota',
  'Kráľová nad Váhom',
  'Kráľová pri Senci',
  'Kraľovany',
  'Kráľovce',
  'Kráľovce - Krnišov',
  'Kráľovičove Kračany',
  'Kráľovský Chlmec',
  'Kraskovo',
  'Krásna Lúka',
  'Krásna Ves',
  'Krasňany',
  'Krásno',
  'Krásno nad Kysucou',
  'Krásnohorská Dlhá Lúka',
  'Krásnohorské Podhradie',
  'Krásnovce',
  'Krásny Brod',
  'Kravany',
  'Kravany',
  'Kravany nad Dunajom',
  'Krčava',
  'Kremná',
  'Kremnica',
  'Kremnické Bane',
  'Kristy',
  'Krišľovce',
  'Krišovská Liesková',
  'Krivá',
  'Kriváň',
  'Krivany',
  'Krivé',
  'Krivoklát',
  'Krivosúd - Bodovka',
  'Kríže',
  'Krížová Ves',
  'Krížovany',
  'Križovany nad Dudváhom',
  'Krná',
  'Krnča',
  'Krokava',
  'Krompachy',
  'Krpeľany',
  'Krškany',
  'Krtovce',
  'Kručov',
  'Krupina',
  'Krušetnica',
  'Krušinec',
  'Krušovce',
  'Kružlov',
  'Kružlová',
  'Kružná',
  'Kružno',
  'Kšinná',
  'Kubáňovo',
  'Kučín',
  'Kučín',
  'Kuchyňa',
  'Kuklov',
  'Kuková',
  'Kukučínov',
  'Kunerad',
  'Kunešov',
  'Kunova Teplica',
  'Kuraľany',
  'Kurima',
  'Kurimany',
  'Kurimka',
  'Kurov',
  'Kusín',
  'Kútniky',
  'Kúty',
  'Kuzmice',
  'Kuzmice',
  'Kvačany',
  'Kvačany',
  'Kvakovce',
  'Kvašov',
  'Kvetoslavov',
  'Kyjatice',
  'Kyjov',
  'Kynceľová',
  'Kysak',
  'Kyselica',
  'Kysta',
  'Kysucké Nové Mesto',
  'Kysucký Lieskovec',
  'Láb',
  'Lackov',
  'Lacková',
  'Lackovce',
  'Lada',
  'Ladce',
  'Ladice',
  'Ladmovce',
  'Ladomerská Vieska',
  'Ladomirov',
  'Ladomirová',
  'Ladzany',
  'Lakšárska Nová Ves',
  'Lascov',
  'Laskár',
  'Lastomír',
  'Lastovce',
  'Laškovce',
  'Látky',
  'Lazany',
  'Lazy pod Makytou',
  'Lažany',
  'Lednica',
  'Lednické Rovne',
  'Legnava',
  'Lehnice',
  'Lehota',
  'Lehota nad Rimavicou',
  'Lehota pod Vtáčnikom',
  'Lehôtka',
  'Lehôtka pod Brehmi',
  'Lechnica',
  'Lekárovce',
  'Leľa',
  'Leles',
  'Lemešany',
  'Lenartov',
  'Lenartovce',
  'Lendak',
  'Lenka',
  'Lentvora',
  'Leopoldov',
  'Lesenice',
  'Lesíček',
  'Lesné',
  'Lesnica',
  'Leštiny',
  'Letanovce',
  'Letničie',
  'Leváre',
  'Levice',
  'Levkuška',
  'Levoča',
  'Ležiachov',
  'Libichava',
  'Licince',
  'Ličartovce',
  'Liesek',
  'Lieskovany',
  'Lieskovec',
  'Lieskovec',
  'Liešno',
  'Liešťany',
  'Lietava',
  'Lietavská Lúčka',
  'Lietavská Svinná - Babkov',
  'Likavka',
  'Limbach',
  'Lipany',
  'Lipník',
  'Lipníky',
  'Lipová',
  'Lipová',
  'Lipovany',
  'Lipovce',
  'Lipové',
  'Lipovec',
  'Lipovec',
  'Lipovník',
  'Lipovník',
  'Liptovská Anna',
  'Liptovská Kokava',
  'Liptovská Lúžna',
  'Liptovská Osada',
  'Liptovská Porúbka',
  'Liptovská Sielnica',
  'Liptovská Štiavnica',
  'Liptovská Teplá',
  'Liptovská Teplička',
  'Liptovské Beharovce',
  'Liptovské Kľačany',
  'Liptovské Matiašovce',
  'Liptovské Revúce',
  'Liptovské Sliače',
  'Liptovský Hrádok',
  'Liptovský Ján',
  'Liptovský Michal',
  'Liptovský Mikuláš',
  'Liptovský Ondrej',
  'Liptovský Peter',
  'Liptovský Trnovec',
  'Lisková',
  'Lišov',
  'Litava',
  'Litmanová',
  'Livina',
  'Livinské Opatovce',
  'Livov',
  'Livovská Huta',
  'Lodno',
  'Lok',
  'Lokca',
  'Lom nad Rimavicou',
  'Lomná',
  'Lomné',
  'Lomnička',
  'Lontov',
  'Lopašov',
  'Lopúchov',
  'Lopušné Pažite',
  'Lošonec',
  'Lovce',
  'Lovča',
  'Lovčica - Trubín',
  'Lovinobaňa',
  'Lozorno',
  'Ložín',
  'Ľubá',
  'Ľubeľa',
  'Lubeník',
  'Ľubica',
  'Ľubietová',
  'Lubina',
  'Ľubiša',
  'Ľubochňa',
  'Ľuboreč',
  'Ľuboriečka',
  'Ľubotice',
  'Ľubotín',
  'Ľubovec',
  'Lúč na Ostrove',
  'Lučatín',
  'Lučenec',
  'Lúčina',
  'Lučivná',
  'Lúčka',
  'Lúčka',
  'Lúčka',
  'Lúčka',
  'Lúčky',
  'Lúčky',
  'Lúčky',
  'Lúčnica nad Žitavou',
  'Ludanice',
  'Ľudovítová',
  'Ludrová',
  'Luhyňa',
  'Lúka',
  'Lukačovce',
  'Lukáčovce',
  'Lukavica',
  'Lukavica',
  'Lukov',
  'Lukovištia',
  'Lúky',
  'Lula',
  'Lupoč',
  'Lutila',
  'Ľutina',
  'Lutiše',
  'Ľutov',
  'Lužany',
  'Lužany pri Topli',
  'Lužianky',
  'Lysá pod Makytou',
  'Lysica',
  'Macov',
  'Mad',
  'Madunice',
  'Magnezitovce',
  'Machulince',
  'Majcichov',
  'Majerovce',
  'Makov',
  'Makovce',
  'Malá Čalomija',
  'Malá Čausa',
  'Malá Čierna',
  'Malá Domaša',
  'Malá Franková',
  'Malá Hradná',
  'Malá Ida',
  'Malá Lehota',
  'Malá Lodina',
  'Malá Mača',
  'Malá nad Hronom',
  'Malá Poľana',
  'Malá Tŕňa',
  'Malacky',
  'Malachov',
  'Málaš',
  'Malatiná',
  'Malatíny',
  'Malcov',
  'Malčice',
  'Malé Borové',
  'Malé Dvorníky',
  'Malé Hoste',
  'Malé Chyndice',
  'Malé Kosihy',
  'Malé Kozmálovce',
  'Malé Kršteňany',
  'Malé Lednice',
  'Malé Leváre',
  'Malé Ludince',
  'Malé Ozorovce',
  'Malé Raškovce',
  'Malé Ripňany',
  'Malé Straciny',
  'Malé Trakany',
  'Malé Uherce',
  'Malé Vozokany',
  'Malé Zálužie',
  'Malé Zlievce',
  'Málinec',
  'Malinová',
  'Malinovo',
  'Malužiná',
  'Malý Cetín',
  'Malý Čepčín',
  'Malý Horeš',
  'Malý Kamenec',
  'Malý Krtíš',
  'Malý Lapáš',
  'Malý Lipník',
  'Malý Slavkov',
  'Malý Slivník',
  'Malý Šariš',
  'Malženice',
  'Maňa',
  'Mankovce',
  'Marcelová',
  'Margecany',
  'Marhaň',
  'Marianka',
  'Markovce',
  'Markuška',
  'Markušovce',
  'Maršová - Rašov',
  'Martin',
  'Martin nad Žitavou',
  'Martinček',
  'Martinová',
  'Martovce',
  'Mašková',
  'Maškovce',
  'Matejovce nad Hornádom',
  'Matiaška',
  'Matiašovce',
  'Matovce',
  'Maťovské Vojkovce',
  'Matúškovo',
  'Matysová',
  'Medovarce',
  'Medvedie',
  'Medveďov',
  'Medzany',
  'Medzev',
  'Medzianky',
  'Medzibrod',
  'Medzibrodie nad Oravou',
  'Medzilaborce',
  'Melčice - Lieskové',
  'Melek',
  'Meliata',
  'Mengusovce',
  'Merašice',
  'Merník',
  'Mestečko',
  'Mestisko',
  'Mičakovce',
  'Mierovo',
  'Miezgovce',
  'Michajlov',
  'Michal na Ostrove',
  'Michal nad Žitavou',
  'Michaľany',
  'Michalok',
  'Michalová',
  'Michalovce',
  'Miklušovce',
  'Miková',
  'Mikulášová',
  'Mikušovce',
  'Mikušovce',
  'Milhosť',
  'Miloslavov',
  'Milpoš',
  'Miňovce',
  'Mirkovce',
  'Miroľa',
  'Mládzovo',
  'Mlynárovce',
  'Mlynčeky',
  'Mlynica',
  'Mlynky',
  'Mníchova Lehota',
  'Mníšek nad Hnilcom',
  'Mníšek nad Popradom',
  'Moča',
  'Močenok',
  'Močiar',
  'Modra',
  'Modra nad Cirochou',
  'Modrany',
  'Modrová',
  'Modrovka',
  'Modrý Kameň',
  'Mojmírovce',
  'Mojš',
  'Mojtín',
  'Mojzesovo',
  'Mokrá Lúka',
  'Mokrance',
  'Mokroluh',
  'Mokrý Háj',
  'Moldava nad Bodvou',
  'Moravany',
  'Moravany nad Váhom',
  'Moravské Lieskové',
  'Moravský Svätý Ján',
  'Most pri Bratislave',
  'Mostová',
  'Mošovce',
  'Moštenica',
  'Mošurov',
  'Motešice',
  'Motyčky',
  'Môlča',
  'Mrázovce',
  'Mučín',
  'Mudroňovo',
  'Mudrovce',
  'Muľa',
  'Muráň',
  'Muránska Dlhá Lúka',
  'Muránska Huta',
  'Muránska Lehota',
  'Muránska Zdychava',
  'Mútne',
  'Mužla',
  'Myjava',
  'Myslina',
  'Mýtna',
  'Mýtne Ludany',
  'Mýto pod Ďumbierom',
  'Nacina Ves',
  'Nadlice',
  'Ňagov',
  'Naháč',
  'Nálepkovo',
  'Námestovo',
  'Nána',
  'Nandraž',
  'Ňárad',
  'Necpaly',
  'Nedanovce',
  'Nedašovce',
  'Neded',
  'Nededza',
  'Nedožery - Brezany',
  'Nechválova  Polianka',
  'Nemce',
  'Nemcovce',
  'Nemcovce',
  'Nemčice',
  'Nemčiňany',
  'Nemecká',
  'Nemečky',
  'Nemešany',
  'Nemšová',
  'Nenince',
  'Neporadza',
  'Neporadza',
  'Nesluša',
  'Nesvady',
  'Neverice',
  'Nevidzany',
  'Nevidzany',
  'Nevoľné',
  'Nezbudská Lúčka',
  'Nimnica',
  'Nitra',
  'Nitra nad Ipľom',
  'Nitrianska Blatnica',
  'Nitrianska Streda',
  'Nitrianske Hrnčiarovce',
  'Nitrianske Pravno',
  'Nitrianske Rudno',
  'Nitrianske Sučany',
  'Nitrica',
  'Nižná',
  'Nižná',
  'Nižná Boca',
  'Nižná Hutka',
  'Nižná Jablonka',
  'Nižná Jedľová',
  'Nižná Kamenica',
  'Nižná Myšľa',
  'Nižná Olšava',
  'Nižná Pisaná',
  'Nižná Polianka',
  'Nižná Rybnica',
  'Nižná Sitnica',
  'Nižná Slaná',
  'Nižná Voľa',
  'Nižné Ladičkovce',
  'Nižné Repaše',
  'Nižné Ružbachy',
  'Nižný Čaj',
  'Nižný Hrabovec',
  'Nižný Hrušov',
  'Nižný Klátov',
  'Nižný Komárnik',
  'Nižný Kručov',
  'Nižný Lánec',
  'Nižný Mirošov',
  'Nižný Orlík',
  'Nižný Skálnik',
  'Nižný Slavkov',
  'Nižný Tvarožec',
  'Nižný Žipov',
  'Nolčovo',
  'Norovce',
  'Nová Baňa',
  'Nová Bašta',
  'Nová Bošáca',
  'Nová Bystrica',
  'Nová Dedina',
  'Nová Dedinka',
  'Nová Dubnica',
  'Nová Kelča',
  'Nová Lesná',
  'Nová Ľubovňa',
  'Nová Polhora',
  'Nová Polianka',
  'Nová Sedlica',
  'Nová Ves',
  'Nová Ves nad Váhom',
  'Nová Ves nad Žitavou',
  'Nová Vieska',
  'Nováčany',
  'Nováky',
  'Nové Hony',
  'Nové Mesto nad Váhom',
  'Nové Sady',
  'Nové Zámky',
  'Novosad',
  'Novoť',
  'Nový Ruskov',
  'Nový Salaš',
  'Nový Svet',
  'Nový Tekov',
  'Nový Život',
  'Nýrovce',
  'Obeckov',
  'Obid',
  'Obišovce',
  'Oborín',
  'Obručné',
  'Obyce',
  'Očkov',
  'Očová',
  'Odorín',
  'Ohrady',
  'Ohradzany',
  'Ochodnica',
  'Ochtiná',
  'Okoč',
  'Okoličná na Ostrove',
  'Okrúhle',
  'Okružná',
  'Olcnava',
  'Oľdza',
  'Olejníkov',
  'Olešná',
  'Oľka',
  'Olováry',
  'Oľšavce',
  'Oľšavica',
  'Oľšavka',
  'Oľšavka',
  'Oľšinkov',
  'Oľšov',
  'Olšovany',
  'Omšenie',
  'Ondavské Matiašovce',
  'Ondrašová',
  'Ondrašovce',
  'Ondrejovce',
  'Opátka',
  'Opatovce',
  'Opatovce nad Nitrou',
  'Opatovská Nová Ves',
  'Opava',
  'Opiná',
  'Opoj',
  'Oponice',
  'Oravce',
  'Orávka',
  'Oravská Jasenica',
  'Oravská Lesná',
  'Oravská Polhora',
  'Oravská Poruba',
  'Oravské Veselé',
  'Oravský Biely Potok',
  'Oravský Podzámok',
  'Ordzovany',
  'Orechová',
  'Orechová Potôň',
  'Oreské',
  'Oreské',
  'Orešany',
  'Orlov',
  'Orovnica',
  'Ortuťová',
  'Osádka',
  'Osadné',
  'Osikov',
  'Oslany',
  'Osrblie',
  'Ostrá Lúka',
  'Ostratice',
  'Ostrov',
  'Ostrov',
  'Ostrovany',
  'Ostrý Grúň',
  'Osturňa',
  'Osuské',
  'Oščadnica',
  'Otrhánky',
  'Otročok',
  'Ovčiarsko',
  'Ovčie',
  'Ozdín',
  'Ožďany',
  'Pača',
  'Padáň',
  'Padarovce',
  'Pakostov',
  'Palárikovo',
  'Palín',
  'Palota',
  'Paňa',
  'Panické Dravce',
  'Paňovce',
  'Papín',
  'Papradno',
  'Parchovany',
  'Parihuzovce',
  'Párnica',
  'Partizánska Ľupča',
  'Partizánske',
  'Pastovce',
  'Pastuchov',
  'Pašková',
  'Paština Závada',
  'Pata',
  'Pataš',
  'Patince',
  'Pavčina Lehota',
  'Pavľany',
  'Pavlice',
  'Pavlová',
  'Pavlova Ves',
  'Pavlovce',
  'Pavlovce',
  'Pavlovce nad Uhom',
  'Pažiť',
  'Pčoliné',
  'Pečeňady',
  'Pečeňany',
  'Pečenice',
  'Pečovská Nová Ves',
  'Peder',
  'Perín - Chym',
  'Pernek',
  'Petrikovce',
  'Petrová',
  'Petrova Lehota',
  'Petrova Ves',
  'Petrovany',
  'Petrovce',
  'Petrovce',
  'Petrovce',
  'Petrovce nad Laborcom',
  'Petrovice',
  'Petrovo',
  'Pezinok',
  'Piešťany',
  'Pichne',
  'Píla',
  'Píla',
  'Píla',
  'Pinciná',
  'Pinkovce',
  'Piskorovce',
  'Pitelová',
  'Plášťovce',
  'Plavé Vozokany',
  'Plavecké Podhradie',
  'Plavecký Mikuláš',
  'Plavecký Peter',
  'Plavecký Štvrtok',
  'Plaveč',
  'Plavnica',
  'Plechotice',
  'Pleš',
  'Plešivec',
  'Plevník - Drienové',
  'Pliešovce',
  'Ploské',
  'Ploské',
  'Pobedim',
  'Počarová',
  'Počúvadlo',
  'Podbiel',
  'Podbranč',
  'Podbrezová',
  'Podhájska',
  'Podhorany',
  'Podhorany',
  'Podhorany',
  'Podhorie',
  'Podhorie',
  'Podhoroď',
  'Podhradie',
  'Podhradie',
  'Podhradie',
  'Podhradík',
  'Podkonice',
  'Podkriváň',
  'Podkylava',
  'Podlužany',
  'Podlužany',
  'Podolie',
  'Podolínec',
  'Podrečany',
  'Podskalie',
  'Podtureň',
  'Podvysoká',
  'Podzámčok',
  'Pohorelá',
  'Pohranice',
  'Pohronská Polhora',
  'Pohronský Bukovec',
  'Pohronský Ruskov',
  'Pochabany',
  'Pokryváč',
  'Poľanovce',
  'Poľany',
  'Poliakovce',
  'Polianka',
  'Polichno',
  'Polina',
  'Poľný Kesov',
  'Poloma',
  'Polomka',
  'Poltár',
  'Poluvsie',
  'Pongrácovce',
  'Poniky',
  'Poprad',
  'Poproč',
  'Poproč',
  'Popudinské Močidľany',
  'Poráč',
  'Poriadie',
  'Porostov',
  'Poruba',
  'Poruba pod Vihorlatom',
  'Porúbka',
  'Porúbka',
  'Porúbka',
  'Porúbka',
  'Poša',
  'Potok',
  'Potok',
  'Potoky',
  'Potôčky',
  'Potônske Lúky',
  'Potvorice',
  'Považany',
  'Považská Bystrica',
  'Povina',
  'Povoda',
  'Povrazník',
  'Pozba',
  'Pozdišovce',
  'Pôtor',
  'Praha',
  'Prakovce',
  'Prašice',
  'Prašník',
  'Pravenec',
  'Pravica',
  'Pravotice',
  'Práznovce',
  'Prečín',
  'Predajná',
  'Predmier',
  'Prenčov',
  'Preseľany',
  'Prestavlky',
  'Prešov',
  'Príbelce',
  'Pribeník',
  'Pribeta',
  'Pribiš',
  'Príbovce',
  'Pribylina',
  'Priechod',
  'Priekopa',
  'Priepasné',
  'Prietrž',
  'Prietržka',
  'Prievaly',
  'Prievidza',
  'Prihradzany',
  'Príkra',
  'Príslop',
  'Prituľany',
  'Proč',
  'Prochot',
  'Prosačov',
  'Prosiek',
  'Prša',
  'Pruské',
  'Prusy',
  'Pružina',
  'Pstriná',
  'Ptičie',
  'Ptrukša',
  'Pucov',
  'Púchov',
  'Pukanec',
  'Pusté Čemerné',
  'Pusté Pole',
  'Pusté Sady',
  'Pusté Úľany',
  'Pušovce',
  'Rabča',
  'Rabčice',
  'Rad',
  'Radatice',
  'Radava',
  'Radimov',
  'Radnovce',
  'Radobica',
  'Radoľa',
  'Radoma',
  'Radošina',
  'Radošovce',
  'Radošovce',
  'Radôstka',
  'Radvaň nad Dunajom',
  'Radvaň nad Laborcom',
  'Radvanovce',
  'Radzovce',
  'Rafajovce',
  'Rajčany',
  'Rajec',
  'Rajecká Lesná',
  'Rajecké Teplice',
  'Rákoš',
  'Rákoš',
  'Raková',
  'Rakovčík',
  'Rakovec nad Ondavou',
  'Rakovice',
  'Rakovnica',
  'Rakovo',
  'Rakša',
  'Rakúsy',
  'Rakytník',
  'Rankovce',
  'Rapovce',
  'Raslavice',
  'Rastislavice',
  'Rašice',
  'Ratka',
  'Ratková',
  'Ratkovce',
  'Ratkovo',
  'Ratkovská Lehota',
  'Ratkovská Suchá',
  'Ratkovské Bystré',
  'Ratnovce',
  'Ratvaj',
  'Ráztočno',
  'Ráztoka',
  'Ražňany',
  'Reca',
  'Regetovka',
  'Rejdová',
  'Reľov',
  'Remeniny',
  'Remetské Hámre',
  'Renčišov',
  'Repejov',
  'Repište',
  'Rešica',
  'Rešov',
  'Revúca',
  'Revúcka Lehota',
  'Riečka',
  'Riečka',
  'Richnava',
  'Richvald',
  'Rimavská Baňa',
  'Rimavská Seč',
  'Rimavská Sobota',
  'Rimavské Brezovo',
  'Rimavské Janovce',
  'Rimavské Zalužany',
  'Rišňovce',
  'Rohov',
  'Rohovce',
  'Rohožník',
  'Rohožník',
  'Rochovce',
  'Rokycany',
  'Rokytov',
  'Rokytov pri Humennom',
  'Rokytovce',
  'Rosina',
  'Roškovce',
  'Roštár',
  'Rovensko',
  'Rovinka',
  'Rovňany',
  'Rovné',
  'Rovné',
  'Rovné',
  'Rozhanovce',
  'Rozložná',
  'Roztoky',
  'Rožkovany',
  'Rožňava',
  'Rožňavské Bystré',
  'Rúbaň',
  'Rudina',
  'Rudinka',
  'Rudinská',
  'Rudlov',
  'Rudná',
  'Rudňany',
  'Rudnianska Lehota',
  'Rudník',
  'Rudník',
  'Rudno',
  'Rudno nad Hronom',
  'Rumanová',
  'Rumince',
  'Runina',
  'Ruská',
  'Ruská Bystrá',
  'Ruská Kajňa',
  'Ruská Nová Ves',
  'Ruská Voľa',
  'Ruská Voľa nad Popradom',
  'Ruská Volová',
  'Ruskov',
  'Ruskovce',
  'Ruskovce',
  'Ruský Hrabovec',
  'Ruský Potok',
  'Ružiná',
  'Ružindol',
  'Ružomberok',
  'Rybany',
  'Rybky',
  'Rybník',
  'Rybník',
  'Rykynčice',
  'Sabinov',
  'Sačurov',
  'Sádočné',
  'Sady nad Torysou',
  'Salka',
  'Santovka',
  'Sap',
  'Sása',
  'Sása',
  'Sasinkovo',
  'Sazdice',
  'Sebedín - Bečov',
  'Sebedražie',
  'Sebechleby',
  'Seč',
  'Sečianky',
  'Sečovce',
  'Sečovská Polianka',
  'Sedliacka Dubová',
  'Sedlice',
  'Sedliská',
  'Sedmerovec',
  'Sejkov',
  'Sekule',
  'Seľany',
  'Selce',
  'Selce',
  'Selce',
  'Selec',
  'Selice',
  'Semerovo',
  'Seňa',
  'Senec',
  'Seniakovce',
  'Senica',
  'Senné',
  'Senné',
  'Senohrad',
  'Sereď',
  'Sielnica',
  'Sihelné',
  'Sihla',
  'Sikenica',
  'Sikenička',
  'Siladice',
  'Silica',
  'Silická Brezová',
  'Silická Jablonica',
  'Sirk',
  'Sirník',
  'Skačany',
  'Skalica',
  'Skalité',
  'Skalka nad Váhom',
  'Skároš',
  'Skerešovo',
  'Sklabiná',
  'Sklabiňa',
  'Sklabinský Podzámok',
  'Sklené',
  'Sklené Teplice',
  'Skrabské',
  'Skýcov',
  'Sládkovičovo',
  'Slančík',
  'Slanec',
  'Slanská Huta',
  'Slanské Nové Mesto',
  'Slaská',
  'Slatina',
  'Slatina nad Bebravou',
  'Slatinka nad Bebravou',
  'Slatinské Lazy',
  'Slatvina',
  'Slavec',
  'Slavkovce',
  'Slavnica',
  'Slavoška',
  'Slavošovce',
  'Sľažany',
  'Slepčany',
  'Sliač',
  'Sliepkovce',
  'Slivník',
  'Slizké',
  'Slopná',
  'Slovany',
  'Slovenská Kajňa',
  'Slovenská Ľupča',
  'Slovenská Nová Ves',
  'Slovenská Ves',
  'Slovenská Volová',
  'Slovenské Ďarmoty',
  'Slovenské Kľačany',
  'Slovenské Krivé',
  'Slovenské Nové Mesto',
  'Slovenský Grob',
  'Slovinky',
  'Smilno',
  'Smižany',
  'Smolenice',
  'Smolinské',
  'Smolnícka Huta',
  'Smolník',
  'Smrdáky',
  'Smrečany',
  'Snakov',
  'Snežnica',
  'Snina',
  'Soblahov',
  'Soboš',
  'Sobotište',
  'Sobrance',
  'Socovce',
  'Sokoľ',
  'Sokoľany',
  'Sokolce',
  'Sokolovce',
  'Soľ',
  'Solčany',
  'Solčianky',
  'Soľnička',
  'Soľník',
  'Sološnica',
  'Somotor',
  'Sopkovce',
  'Spišská Belá',
  'Spišská Nová Ves',
  'Spišská Stará Ves',
  'Spišská Teplica',
  'Spišské Bystré',
  'Spišské Hanušovce',
  'Spišské Podhradie',
  'Spišské Tomášovce',
  'Spišské Vlachy',
  'Spišský Hrhov',
  'Spišský Hrušov',
  'Spišský Štiavnik',
  'Spišský Štvrtok',
  'Stakčín',
  'Stakčínska Roztoka',
  'Stanča',
  'Stankovany',
  'Stankovce',
  'Stará Bašta',
  'Stará Bystrica',
  'Stará Halič',
  'Stará Huta',
  'Stará Kremnička',
  'Stará Lehota',
  'Stará Lesná',
  'Stará Ľubovňa',
  'Stará Myjava',
  'Stará Turá',
  'Stará Voda',
  'Staré',
  'Staré Hory',
  'Starina',
  'Starý Hrádok',
  'Starý Tekov',
  'Staškov',
  'Staškovce',
  'Stebnícka Huta',
  'Stebník',
  'Stožok',
  'Stráňany',
  'Stráňavy',
  'Stráne pod Tatrami',
  'Stránska',
  'Stránske',
  'Stratená',
  'Stráža',
  'Strážne',
  'Strážske',
  'Strečno',
  'Streda nad Bodrogom',
  'Stredné Plachtince',
  'Strekov',
  'Strelníky',
  'Stretava',
  'Stretavka',
  'Streženice',
  'Strihovce',
  'Stročín',
  'Stropkov',
  'Studená',
  'Studenec',
  'Studienka',
  'Stuľany',
  'Stupava',
  'Stupné',
  'Sučany',
  'Sudince',
  'Súdovce',
  'Suchá Dolina',
  'Suchá Hora',
  'Suchá nad Parnou',
  'Sucháň',
  'Suché',
  'Suché Brezovo',
  'Suchohrad',
  'Sukov',
  'Sulín',
  'Súľov - Hradná',
  'Súlovce',
  'Sušany',
  'Sútor',
  'Svätá Mária',
  'Svätoplukovo',
  'Svätuš',
  'Svätuše',
  'Svätý Anton',
  'Svätý Jur',
  'Svätý Kríž',
  'Svätý Peter',
  'Svederník',
  'Sverepec',
  'Sveržov',
  'Svetlice',
  'Svidnička',
  'Svidník',
  'Svinia',
  'Svinica',
  'Svinice',
  'Svinná',
  'Svit',
  'Svodín',
  'Svrbice',
  'Svrčinovec',
  'Šahy',
  'Šajdíkove Humence',
  'Šaľa',
  'Šalgočka',
  'Šalgovce',
  'Šalov',
  'Šambron',
  'Šamorín',
  'Šamudovce',
  'Šandal',
  'Šarbov',
  'Šarišská Poruba',
  'Šarišská Trstená',
  'Šarišské Bohdanovce',
  'Šarišské Čierne',
  'Šarišské Dravce',
  'Šarišské Jastrabie',
  'Šarišské Michaľany',
  'Šarišské Sokolovce',
  'Šarišský Štiavnik',
  'Šarkan',
  'Šarovce',
  'Šašová',
  'Šaštín - Stráže',
  'Šávoľ',
  'Šelpice',
  'Šemetkovce',
  'Šemša',
  'Šenkvice',
  'Šiatorská Bukovinka',
  'Šiba',
  'Šíd',
  'Šimonovce',
  'Šindliar',
  'Šintava',
  'Šípkov',
  'Šípkové',
  'Širákov',
  'Širkovce',
  'Široké',
  'Šišov',
  'Šivetice',
  'Šmigovec',
  'Šoltýska',
  'Šoporňa',
  'Špačince',
  'Špania Dolina',
  'Španie Pole',
  'Šrobárová',
  'Štefanov',
  'Štefanov nad Oravou',
  'Štefanová',
  'Štefanovce',
  'Štefanovce',
  'Štefanovičová',
  'Štefurov',
  'Šterusy',
  'Štiavnické Bane',
  'Štiavnička',
  'Štiavnik',
  'Štitáre',
  'Štítnik',
  'Štós',
  'Štôla',
  'Štrba',
  'Štrkovec',
  'Štúrovo',
  'Štvrtok',
  'Štvrtok na Ostrove',
  'Šuja',
  'Šuľa',
  'Šumiac',
  'Šuňava',
  'Šurany',
  'Šurianky',
  'Šurice',
  'Šúrovce',
  'Šútovce',
  'Šútovo',
  'Švábovce',
  'Švedlár',
  'Švošov',
  'Tachty',
  'Tajná',
  'Tajov',
  'Ťapešovo',
  'Tarnov',
  'Tašuľa',
  'Tatranská Javorina',
  'Tehla',
  'Tekolďany',
  'Tekovská Breznica',
  'Tekovské Lužany',
  'Tekovské Nemce',
  'Tekovský Hrádok',
  'Telgárt',
  'Telince',
  'Temeš',
  'Teplička',
  'Teplička nad Váhom',
  'Tepličky',
  'Teplý Vrch',
  'Terany',
  'Terchová',
  'Teriakovce',
  'Terňa',
  'Tesáre',
  'Tesárske Mlyňany',
  'Tešedíkovo',
  'Tibava',
  'Tichý Potok',
  'Timoradza',
  'Tisinec',
  'Tisovec',
  'Tlmače',
  'Točnica',
  'Tokajík',
  'Tomášikovo',
  'Tomášov',
  'Tomášovce',
  'Tomášovce',
  'Topoľa',
  'Topoľčany',
  'Topoľčianky',
  'Topoľnica',
  'Topoľníky',
  'Topoľovka',
  'Toporec',
  'Tornaľa',
  'Torysa',
  'Torysky',
  'Tovarné',
  'Tovarnianska Polianka',
  'Tovarníky',
  'Tôň',
  'Trakovice',
  'Trávnica',
  'Trávnik',
  'Trebatice',
  'Trebejov',
  'Trebeľovce',
  'Trebichava',
  'Trebišov',
  'Trebostovo',
  'Trebušovce',
  'Trenč',
  'Trenčianska Teplá',
  'Trenčianska Turná',
  'Trenčianske Bohuslavice',
  'Trenčianske Jastrabie',
  'Trenčianske Mitice',
  'Trenčianske Stankovce',
  'Trenčianske Teplice',
  'Trenčín',
  'Trhová Hradská',
  'Trhovište',
  'Trnava',
  'Trnavá Hora',
  'Trnava pri Laborci',
  'Trnávka',
  'Trnávka',
  'Tŕnie',
  'Trnkov',
  'Trnovec',
  'Trnovec nad Váhom',
  'Trnovo',
  'Tročany',
  'Trpín',
  'Trsťany',
  'Trstená',
  'Trstená na Ostrove',
  'Trstené',
  'Trstené pri Hornáde',
  'Trstice',
  'Trstín',
  'Tuhár',
  'Tuhrina',
  'Tuchyňa',
  'Tulčík',
  'Tupá',
  'Turá',
  'Turany',
  'Turcovce',
  'Turček',
  'Turčianky',
  'Turčianska Štiavnička',
  'Turčianske Jaseno',
  'Turčianske Kľačany',
  'Turčianske Teplice',
  'Turčiansky Ďur',
  'Turčiansky Peter',
  'Turčok',
  'Turecká',
  'Tureň',
  'Turie',
  'Turík',
  'Turňa nad Bodvou',
  'Turnianska Nová Ves',
  'Turová',
  'Turzovka',
  'Tušice',
  'Tušická Nová Ves',
  'Tužina',
  'Tvarožná',
  'Tvrdomestice',
  'Tvrdošín',
  'Tvrdošovce',
  'Ubľa',
  'Úbrež',
  'Udavské',
  'Udiča',
  'Údol',
  'Uhliská',
  'Úhorná',
  'Uhorská Ves',
  'Uhorské',
  'Uhrovec',
  'Uhrovské Podhradie',
  'Úľany nad Žitavou',
  'Ulič',
  'Uličské Krivé',
  'Uloža',
  'Uňatín',
  'Unín',
  'Urmince',
  'Utekáč',
  'Uzovce',
  'Uzovská Panica',
  'Uzovské Pekľany',
  'Uzovský Šalgov',
  'Vaďovce',
  'Vagrinec',
  'Váhovce',
  'Vajkovce',
  'Valaliky',
  'Valaská',
  'Valaská Belá',
  'Valaská Dubová',
  'Valča',
  'Valentovce',
  'Valice',
  'Valkovce',
  'Vaľkovňa',
  'Vaniškovce',
  'Vápeník',
  'Varadka',
  'Varechovce',
  'Varhaňovce',
  'Varín',
  'Vasiľov',
  'Vavrečka',
  'Vavrinec',
  'Vavrišovo',
  'Važec',
  'Včelince',
  'Večelkov',
  'Vechec',
  'Veľaty',
  'Velčice',
  'Veličná',
  'Veľká Čalomija',
  'Veľká Čausa',
  'Veľká Čierna',
  'Veľká Dolina',
  'Veľká Franková',
  'Veľká Hradná',
  'Veľká Ida',
  'Veľká Lehota',
  'Veľká Lesná',
  'Veľká Lodina',
  'Veľká Lomnica',
  'Veľká Lúka',
  'Veľká Mača',
  'Veľká nad Ipľom',
  'Veľká Paka',
  'Veľká Tŕňa',
  'Veľká Ves',
  'Veľká Ves nad Ipľom',
  'Veľké Bierovce',
  'Veľké Blahovo',
  'Veľké Borové',
  'Veľké Dravce',
  'Veľké Držkovce',
  'Veľké Dvorany',
  'Veľké Dvorníky',
  'Veľké Hoste',
  'Veľké Chlievany',
  'Veľké Chyndice',
  'Veľké Kapušany',
  'Veľké Kosihy',
  'Veľké Kostoľany',
  'Veľké Kozmálovce',
  'Veľké Kršteňany',
  'Veľké Leváre',
  'Veľké Lovce',
  'Veľké Ludince',
  'Veľké Orvište',
  'Veľké Ozorovce',
  'Veľké Pole',
  'Veľké Raškovce',
  'Veľké Revištia',
  'Veľké Ripňany',
  'Veľké Rovné',
  'Veľké Slemence',
  'Veľké Straciny',
  'Veľké Teriakovce',
  'Veľké Trakany',
  'Veľké Turovce',
  'Veľké Uherce',
  'Veľké Úľany',
  'Veľké Vozokany',
  'Veľké Zálužie',
  'Veľké Zlievce',
  'Veľkrop',
  'Veľký Biel',
  'Veľký Blh',
  'Veľký Cetín',
  'Veľký Čepčín',
  'Veľký Ďur',
  'Veľký Folkmar',
  'Veľký Grob',
  'Veľký Horeš',
  'Veľký Kamenec',
  'Veľký Klíž',
  'Veľký Krtíš',
  'Veľký Kýr',
  'Veľký Lapáš',
  'Veľký Lipník',
  'Veľký Lom',
  'Veľký Meder',
  'Veľký Slavkov',
  'Veľký Slivník',
  'Veľký Šariš',
  'Veľopolie',
  'Velušovce',
  'Vernár',
  'Veselé',
  'Veterná Poruba',
  'Vidiná',
  'Vieska',
  'Vieska',
  'Vieska nad Blhom',
  'Vieska nad Žitavou',
  'Vígľaš',
  'Vígľašská Huta - Kalinka',
  'Vikartovce',
  'Vinica',
  'Viničky',
  'Viničné',
  'Vinné',
  'Vinodol',
  'Vinohrady nad Váhom',
  'Vinosady',
  'Virt',
  'Vislanka',
  'Vislava',
  'Visolaje',
  'Višňov',
  'Višňové',
  'Višňové',
  'Višňové',
  'Vištuk',
  'Vitanová',
  'Víťaz',
  'Víťazovce',
  'Vítkovce',
  'Vlača',
  'Vladiča',
  'Vlachovo',
  'Vlachy',
  'Vlčany',
  'Vlčkovce',
  'Vlkanová',
  'Vlkas',
  'Vlková',
  'Vlkovce',
  'Vlky',
  'Vlkyňa',
  'Voderady',
  'Vojany',
  'Vojčice',
  'Vojka',
  'Vojka nad Dunajom',
  'Vojkovce',
  'Vojňany',
  'Vojnatina',
  'Vojtovce',
  'Voľa',
  'Volica',
  'Volkovce',
  'Voznica',
  'Vozokany',
  'Vozokany',
  'Vráble',
  'Vrádište',
  'Vrakúň',
  'Vranov nad Topľou',
  'Vrbnica',
  'Vrbov',
  'Vrbová nad Váhom',
  'Vrbovce',
  'Vrbové',
  'Vrbovka',
  'Vrchteplá',
  'Vrícko',
  'Vršatské Podhradie',
  'Vrútky',
  'Vtáčkovce',
  'Výborná',
  'Výčapy - Opatovce',
  'Vydrany',
  'Vydrná',
  'Vydrník',
  'Vyhne',
  'Východná',
  'Výrava',
  'Vysočany',
  'Vysoká',
  'Vysoká',
  'Vysoká nad Kysucou',
  'Vysoká nad Uhom',
  'Vysoká pri Morave',
  'Vysoké Tatry',
  'Vyškovce',
  'Vyškovce nad Ipľom',
  'Vyšná Boca',
  'Vyšná Hutka',
  'Vyšná Jablonka',
  'Vyšná Jedľová',
  'Vyšná Kamenica',
  'Vyšná Myšľa',
  'Vyšná Olšava',
  'Vyšná Pisaná',
  'Vyšná Polianka',
  'Vyšná Rybnica',
  'Vyšná Sitnica',
  'Vyšná Slaná',
  'Vyšná Šebastová',
  'Vyšná Voľa',
  'Vyšné Ladičkovce',
  'Vyšné nad Hronom',
  'Vyšné Nemecké',
  'Vyšné Remety',
  'Vyšné Repaše',
  'Vyšné Ružbachy',
  'Vyšné Valice',
  'Vyšný Čaj',
  'Vyšný Hrabovec',
  'Vyšný Hrušov',
  'Vyšný Kazimír',
  'Vyšný Klátov',
  'Vyšný Komárnik',
  'Vyšný Kručov',
  'Vyšný Kubín',
  'Vyšný Medzev',
  'Vyšný Mirošov',
  'Vyšný Orlík',
  'Vyšný Skálnik',
  'Vyšný Slavkov',
  'Vyšný Tvarožec',
  'Vyšný Žipov',
  'Zábiedovo',
  'Záborie',
  'Záborské',
  'Zádiel',
  'Zádor',
  'Záhor',
  'Záhorce',
  'Záhorská Ves',
  'Záhradné',
  'Zacharovce',
  'Zákamenné',
  'Zákopčie',
  'Zalaba',
  'Zálesie',
  'Zálesie',
  'Zalužice',
  'Zamarovce',
  'Zámutov',
  'Záriečie',
  'Záskalie',
  'Zatín',
  'Závada',
  'Závada',
  'Závada',
  'Závadka',
  'Závadka',
  'Závadka',
  'Závadka nad Hronom',
  'Zavar',
  'Závažná Poruba',
  'Závod',
  'Zázrivá',
  'Zbehňov',
  'Zbehy',
  'Zboj',
  'Zbojné',
  'Zborov',
  'Zborov nad Bystricou',
  'Zbrojníky',
  'Zbudská Belá',
  'Zbudské Dlhé',
  'Zbudza',
  'Zbyňov',
  'Zeleneč',
  'Zemianska Olča',
  'Zemianske Kostoľany',
  'Zemianske Podhradie',
  'Zemianske Sady',
  'Zemiansky Vrbovok',
  'Zemné',
  'Zemplín',
  'Zemplínska Nová Ves',
  'Zemplínska Široká',
  'Zemplínska Teplica',
  'Zemplínske Hámre',
  'Zemplínske Hradište',
  'Zemplínske Jastrabie',
  'Zemplínske Kopčany',
  'Zemplínsky Branč',
  'Zlatá Baňa',
  'Zlatá Idka',
  'Zlaté',
  'Zlaté Klasy',
  'Zlaté Moravce',
  'Zlatná na Ostrove',
  'Zlatník',
  'Zlatníky',
  'Zlatno',
  'Zlatno',
  'Zliechov',
  'Zohor',
  'Zombor',
  'Zubák',
  'Zuberec',
  'Zubné',
  'Zubrohlava',
  'Zvolen',
  'Zvolenská Slatina',
  'Zvončín',
  'Žabokreky',
  'Žabokreky nad Nitrou',
  'Žakarovce',
  'Žakovce',
  'Žalobín',
  'Žarnov',
  'Žarnovica',
  'Žaškov',
  'Žbince',
  'Ždaňa',
  'Ždiar',
  'Žehňa',
  'Žehra',
  'Železná Breznica',
  'Železník',
  'Želiezovce',
  'Želmanovce',
  'Želovce',
  'Žemberovce',
  'Žemliare',
  'Žiar',
  'Žiar',
  'Žiar nad Hronom',
  'Žibritov',
  'Žihárec',
  'Žikava',
  'Žilina',
  'Žíp',
  'Žipov',
  'Žirany',
  'Žitavany',
  'Žitavce',
  'Žitná - Radiša',
  'Žlkovce',
  'Župčany',
  'Župkov',
  
      ]

      



    let starostovia = [
'Jaroslav Maslen',
'Irena Hanobiková',
'Igor Németh',
'Ján Novotný',
'Stanislav Lapko',
'Ľubomír Hrivnák',
'Stanislav Volanský',
'Michal Križan',
'Milan Koromház',
'Radoslav Ťapušík',
'Peter Puss',
'Tomáš Jurečko',
'Maroš Barta',
'Daniel Fábián',
'Zuzana Toporcerová',
'Katarína Töröková',
'Martina Hliboká',
'Martin Matys',
'Jana Gregušová',
'Peter Ďurica',
'Jaroslav Benda',
'Michal Chovanec',
'Katarína Zlámalová',
'Helena Vonyiková',
'Ladislav Kosztyu',
'Jozef Nemčík',
'František Korečko',
'Ľubica Kuková',
'Stanislav Gál',
'Pavol  Hric',
'Ivan Patoprstý',
'František Genco',
'Oto Virág',
'Vladimír Mruz',
'Michal Sekerák',
'Alojz Štrba',
'Jozef Benkó',
'Juraj Bertalan',
'Róbert Chaban',
'Jozef Mlynár',
'Peter Bálint',
'Frigyes Matus',
'František Šlang',
'Tatiana Julinyová',
'Miloš Rybár',
'Rudolfa Novotná',
'Ľudmila Ďurčáková',
'Branislav Babirád',
'Ján Nosko',
'Nadežda Babiaková',
'Stanislav Maloš',
'Pavol Santoris',
'Ľudovít Sütő',
'Richard Szajko',
'Boris Hanuščak',
'Tibor Černák',
'Zlatica Groschová',
'Václav Hudák',
'Ján Serbin',
'Pavol Tamáš',
'Peter Báthory',
'Ľubomír Dekan',
'Gabriel Bodnár',
'Peter Hencz',
'Ján Máth',
'Roland Labancz',
'Peter Burčo',
'Daniel Hladký',
'Zuzana Škotková',
'Jozef Gmiterko',
'Klaudia Pintérová',
'Matúš Krajči',
'Igor Kapusta',
'Ján Vajda',
'Mário Žáčik',
'Marcel Sopoliga',
'Ivan Očenáš',
'Zoltán Marcinkó',
'Ľubomír Varga',
'Mária Jankovičová',
'Jozef Kostura',
'Monika Zlesíková',
'Ján Prekop',
'Ondrej Pravda',
'Ján Martinovič',
'Ladislav Šotík',
'Jaroslav Pepucha',
'Štefan Minčák',
'Miroslav Halás',
'Milan Remšík',
'Viera Pavlišková',
'Katarína Srnková',
'Richard Červienka',
'Anton Leššo',
'Miroslav Černák',
'Alexander Kalán',
'Gabriel Timoranský',
'Martin Baran',
'Zoltán Varga',
'Ľubomír Zatroch',
'Luděk Hamšík',
'Pavol Azari',
'Ladislav Jurčák',
'Irena Skladanová',
'Iveta Paulová',
'Ján Pivovarniček',
'Rastislav Nemečkay',
'Szabolcs Kremmer',
'Marián Novák',
'Ladislav Noskó',
'Stanislav Knížat',
'Juraj Drdák',
'Alfréd Kuczman',
'Terézia Földváryová',
'Michal Kontra',
'Rastislav Pero',
'Ľuboš Sliško',
'Gabriel Seman',
'Karol Čičmanec',
'Juraj Gmitro',
'Marek Chorváth',
'Juraj Csörnök',
'Danka Ďuriačová',
'Anton Grobarčík',
'Ladislav Staroň',
'Ladislav Sedlák',
'Jana Bažíková',
'Elena Szabóová',
'Tamás Világi',
'Marcela Filová',
'Jana Pagáčová',
'František Jusko',
'Dušan Zelizňák',
'Zuzana Fitosová',
'Monika Aradi',
'Jozef Pavličko',
'Marta Gamrátová',
'Miroslav Sučák',
'Mária Kázmérová',
'Peter Hajdúch',
'Vladimíra Rišková',
'Ágnes Takács',
'Jozef Stankovský',
'František Tám',
'Igor Bojnanský',
'Atila Bohács',
'Peter Múčka',
'Pavol Mackovčín',
'Martin Rác',
'František Hlavatý',
'Ladislav Vanko',
'Marcela Pavlásková',
'Jaroslav Kopčan',
'Ľubica Hasidlová',
'Miroslav Paulen',
'Blanka Matovičová',
'Ivan Šiška',
'Róbert Macek',
'Anna Kratochvílová',
'Anna Tünde Vargová',
'Štefan Mirják',
'Daniel Juráček',
'Branislav Pajda',
'Dionýz Szabó',
'Andrea Baláková',
'Vojtech Ičo',
'Ivana Kolesnáčová',
'Július Kurča',
'Andrea Šulíková',
'Matúš Vallo',
'Gabriela Ferenčáková',
'Ľubica Kolková',
'Dárius Krajčír',
'Martin Zaťovič',
'Jozef Uhler',
'Dana Čahojová',
'Lukáš Baňacký',
'Rudolf Kusý',
'Ján Hrčka',
'Zoltán Pék',
'Michal Drotován',
'Lucia Tuleková Henčelová',
'Martin Chren',
'Zuzana Aufrichtová',
'Michal  Vlček',
'Martin Kuruc',
'Jozef Krúpa',
'Peter Baliak',
'Jaroslav Hric Jančo',
'Marek Balog',
'Juraj Tencer',
'Radoslav Nemec',
'Ľudmila Nováková',
'Jozef Šoltés',
'Ján Zubaľ',
'Ondrej Kuhajda',
'Dušan Duga',
'Peter Tóth',
'Pavel Mylan',
'Anna Giczeiová',
'Ladislav Matejčík',
'Iveta Brezianská',
'Mária Baloghová',
'Ján Šatara',
'Slavomír Brendza',
'Branislav Knechta',
'Monika Leľová',
'Tomáš Abel',
'Iveta Rosová',
'Ladislav Lukáč',
'Jaroslav Ciran',
'Miroslav Solomon',
'Marián Ujmiak',
'Jozef Hodoši',
'Peter Tomčufčík',
'Peter Bučko',
'Mária Gumanová',
'Danuše Francisciová',
'Žaneta Lichnerová',
'Anna Krídlová',
'Anton Zima',
'Stanislava Zervanová',
'Tatiana Szabóová',
'Jaroslav Kalmár',
'Jozef Šimeček',
'Mária Petreková',
'Alexander Hubač',
'Dagmar Mikudíková',
'Tibor Garay',
'Michaela Sabolová',
'Ján  Karkó',
'Rastislav Kurinec',
'František Moravec',
'Martina Kožiaková',
'Vojtech Staňo',
'Marian Čerpák',
'Lóránt Juhász',
'Ivana Erteľová',
'Ján Lörinc',
'Jozef Savkuliak',
'Vincent Koňak',
'Miloš Herceg',
'Jaroslav Palička',
'Marcela Pavesková',
'Lýdia Mikulová',
'Viera Maršalková',
'Dezider Szakó',
'Peter Taiš',
'Václav Ličko',
'Zoltán Végh',
'Daniel Jurek',
'Jozef Mohňanský',
'Miroslav Malatinec',
'Marian Alberty',
'Miroslav Korečko',
'František Žiga',
'Ľubomír Hreha',
'Filip Lukáč',
'Zdenka Maršalová',
'Radoslav Palinský',
'Miroslav Minárčik',
'Marek Kováč',
'Štefan Rafajlovič',
'Dušan Málik',
'Miriam Mokošová',
'Boris Sedmák',
'Martin Kubík',
'Ladislav Vrabeľ',
'Jozef Ligač',
'Viliam Popaďák',
'Karol Bari',
'Ladislav Slovjak',
'Helena Madzinová',
'Ján Čerešník',
'Margita Boďová',
'Róbert Grešo',
'Maroš Sagan',
'Štefan Mjartan',
'Ľudovít Kravec',
'Ján Bodrucký',
'Peter Vanek',
'Jozef Melicher',
'Jozef Mikuška',
'Helena Zjanová',
'Milan Moroz',
'Ján Sliacky',
'Milan Gura',
'Erika Ondrejková',
'Miloš Seneši',
'Ludovít Viglaš',
'Milan Greguš',
'Vojtech Bodor',
'Emil Imro',
'Lívia Bugárová',
'Andrej Dragula',
'Zoltán Molnár',
'Adrián Karkusz',
'Michal Rečka',
'Vladislav Uličný',
'Martin Královič',
'Robert Lederleitner',
'Eva Černeková',
'Dušan Bublavý',
'Marian Csákvári',
'Marta Tušová',
'Anna Gulášová',
'Henrik Tóth',
'Stanislav Mráz',
'Lukáš Macák',
'Jozef Baranovič',
'Róbert Kupeček',
'Milan Gregáň',
'Anton Laca',
'Daniel Hučko',
'Vojtech Ádám',
'Juraj Čelko',
'Ján Petroch',
'Ján Kožlej',
'Jana Sabóvá',
'Jozef Karika',
'Richard Masný',
'Zuzana Študencová',
'Jaroslav Bajužik',
'Pavel Kmeť',
'Radovan Bobula',
'Peter  Stuchlý',
'Silvia Žinčáková',
'Angela Kálmánová',
'Peter Tričák',
'Pavol Džačovský',
'Radoslav Palášthy',
'Martin Husár',
'Pavol Spodník',
'Marián Mihálik',
'Miroslav Kráľ',
'Alena Geregová',
'Štefan Džurný',
'Ivan Miko',
'Vincent Hajdók',
'Dušan Vilenik',
'Iveta Michalíková',
'Csaba Földes',
'Ladislav Jámbor',
'Dušan Horák',
'Iveta Potočná',
'Marta Vozáriková',
'Zuzana Csadyová',
'Pavol Gomola',
'Milan Švec',
'Vladislav Dvorjak',
'Vladimír Vinco',
'František Budovec',
'Svetlana Šufliarska',
'Július Czapala',
'Erzsébet Janík',
'Daniela Tretinová',
'Michal Didik',
'Július Tkáč',
'Stanislav Matta',
'Ján Hubay',
'Zuzana Chorváthová',
'Alexander Szöllös',
'Ľuboš Cima',
'Anton Cuprák',
'Štefan Škraban',
'Daniel Ščavnický',
'Miroslav Výrostek',
'Miroslav Ďanovský',
'Ján Cmár',
'Ján Kiš',
'Jozef Vaľko',
'Adrianna Gergely Papp',
'Peter Pichoňský',
'Gabriela Gönczölová',
'Viera Belanová',
'Milan Červenka',
'Karol Zachar',
'Jozef Bucha',
'Attila Kürthy',
'Ľubomíra Klepáčová',
'Vladislav Bašista',
'Ľubica Voľanská',
'Ján Šufliarský',
'Pavel Šulek',
'Dana Lančaričová',
'Ján Baláž',
'Ladislav Chudoba',
'Miroslav Haverla',
'Kristína Jakócsová',
'Ivan Kohút',
'Vladimír Pružinec',
'Pavel Drugda',
'Martin Fronc',
'Michal Krško',
'Peter Fandl',
'Helena Dzurinová',
'Ján Kamas',
'Pavol Tóth',
'Tomáš Novák',
'Ľubica Zubková',
'Ján Kníž',
'Dana Veveričíková',
'Zdena Jurčíková',
'Jaroslav Sadiv',
'František Adamec',
'Mikuláš Csoma',
'Milan Jakubík',
'René Blanárik',
'Miroslav Remeník',
'Jozef Boráros',
'Vladimír Vančišin',
'Ján Slovák',
'Milan Panáček',
'Slavomíra Melišová',
'Jozef Mruškovič',
'Štefan Kamenický',
'Zsolt Régi',
'Lukáš Pekara',
'Marek Dekan',
'Viera Hudíková',
'Peter Šujak',
'Oto Hudec',
'Miroslav Kopčan',
'Zdenka Furdová',
'Ľuboš Šúry',
'Ľuboslav Dobrocký',
'Rudolf Pleva',
'Ľubica Ďuricová',
'Katarína Lajčiaková',
'Milan Pračko',
'Andrea Murgašová',
'Jozef Čapkovič',
'Martin Dolinský',
'Miloslav Krajčík',
'Tomáš Bartovič',
'Adam Alakša',
'Ľubomíra Kasalová',
'Marián Paulisz',
'Juliana Belicová',
'Ján Maršala',
'Cyril Bartók',
'Ľudovít Kovács',
'Milan Rafael',
'Juraj Hamaj',
'Gabriela Hudecová',
'Stanislava Zacharová',
'Kvetoslava Šimorová',
'Izabela Mezőová',
'Dagmar Jakubcová',
'Mária Jaďuďová',
'Oskár Bereczk',
'Peter Zelník',
'František Dora',
'Iveta Balšianková',
'Ján Prílepok',
'Ján Križan',
'Mário Beblavý',
'Ivan Solár',
'Róbert Potocký',
'Tomáš Horváth',
'Miroslava Ondreášová',
'Antónia Foltánová',
'Mária Mozolová',
'František Matušík',
'Martina Bednárová',
'Miroslav Daňo',
'Martina Grgačová Kocová',
'Tibor Jasovsky',
'Miroslav Ledecký',
'Peter Faltin',
'Krisztián Kovács',
'Eva Gáborová',
'Renáta Mrázová',
'Peter Švoňava',
'Igor Birčák',
'Peter Tomko',
'Tibor Kočiš',
'Ivana Drígeľová',
'Ján Brozman',
'Jaroslav Mego',
'Endre Vincze',
'Tibor Balázs',
'Ján Juhás',
'Slavomír Baláž',
'Mária Duszová',
'Miroslav Škrabák',
'Milan Hudák',
'Peter Wolf',
'Jozef Petrek',
'Jozef Ostrodický',
'Anton Prechádzka',
'Ľudovít Ružička',
'Miloš Vaňušaník',
'Miroslav Michalčík',
'Dana Dorothea Mikulová',
'Milan Lettrich',
'Anna Janovicová',
'Annamária Gotlíbetová',
'Ladislav Timčo',
'Vladimír Janičina',
'František Šimon',
'Ondrej Hovančík',
'Janka Slobodníková',
'Stanislav Bajužik',
'Elena Grňová',
'Mária Koláriková',
'Dušan Strieborný',
'Jozef Bodnár',
'Jozef Šamaj',
'Barbora Ježiková',
'Andrej Hamran',
'Katarína Balážová',
'Milada Chlastáková',
'Štefan Jurčík',
'Zoltán Hájos',
'Mária Csibová',
'Jozef Potoma',
'Martina Bohušová',
'Miroslav Mikeľ',
'Iveta Hadašová',
'Anton Ondrásky',
'Ondrej Valik',
'Ivana Opinová',
'Eva Egryová',
'František Košecký',
'Eva Srncová',
'Gabriel Čverčko',
'Maroš Nemeček',
'Csaba Simkó',
'Branislav Becík',
'Gabriela Timková',
'Miroslav Čerňanec',
'Michal Bodnár',
'Vlasta Csomorová',
'Miloslava Fedorová',
'Tibor Sklenárik',
'Jana Tchuriková',
'Attila Agócs',
'Michal Muránsky',
'Terézia Gmitrová',
'Milan Sopóci',
'Michal Hanečák',
'Martin Sivák',
'Matej Straka',
'Ján Mikula',
'Miroslav Leško',
'Iván Fenes',
'Martin Ceľuch',
'Martin Rybecký',
'Peter Paška',
'Miroslav Kubáň',
'Denisa Ivančíková',
'Michal Materný',
'Jozef Martinček',
'František Szőcs',
'Jozef Hazlinger',
'Patrik Rusňák',
'Dušan Tomaško',
'Zoltán Jankóšik',
'Zoltán Kišantal',
'Tibor Balázs',
'Michal Fedor',
'Lillian Bronďošová',
'Monika Lévaiová',
'Ondrej Borbáš',
'Levente Hubay',
'Laura Durančíková',
'Július Agócs',
'Vojtech Pataki',
'Vladimír Tejiščák',
'Ondrej Ševcov',
'Ján Hroboň',
'Zuzana Bochová',
'Ján Rubis',
'Štefan Chudý',
'Jarmila Pavlíková',
'Milan Mlynár',
'Ľuboš Kolárik',
'Gejza Balog',
'Jozef Cút',
'Peter Pitoňák',
'Renata Hrnčiarová',
'Slavomíra Daráková',
'Štefan Mulik',
'Martin Petík',
'Denisa Vargová',
'Alojz Lajčin',
'Michal Prejsa',
'Peter Gábor',
'Erika Herčúthová',
'Július Farkas',
'Ľuboš Koma',
'Ivan Poprocký',
'Jaroslav Bennár',
'Pavol Nosek',
'Zuzana Mokryšová',
'Alexander Udvardy',
'Monika Bjalončíková',
'Miloš Madila',
'Ludmila Goldbergerová',
'Silvia Grúberová',
'Alena Havrilová',
'Ladislav Šimkovič',
'Miloš Barcal',
'Matilda Jakubíková',
'Ján Grega-Jakub',
'Ľudmila Veľasová',
'Štefan Straka',
'Božena Cmorejová',
'Maroš Jantek',
'Miloš Augustiňák',
'Henrieta Ivanová',
'Vladimír Kováč',
'Iveta Žilovcová',
'Stanislav Viňarský',
'Pavol Jabrocký',
'Milan Ščerba',
'Marianna Šimková',
'Július Buček',
'František Olah',
'Tibor Theis',
'Peter Hyriak',
'Viera Nemcová',
'Lýdia Šomšáková',
'Matúš Tomáš',
'Martin Martaus',
'Slavomír Rusnák',
'Lukáš Grejták',
'Martin Ivan',
'Jozef Semanek',
'Miroslav Mackanič',
'Ondrej Snopko',
'Anna Filipová',
'Marián Brnušák',
'Miloš Čobrda',
'Karina Holešová',
'Vladimír Mikuláš',
'Milena Naštová Hladová',
'Miroslav Džuba',
'Miroslav Kollár',
'Viktor Selep',
'Ľubomír Kačír',
'Otokár Jeremiaš',
'Helena Kráľová',
'Roman Lebeda',
'Katarína Jakabová',
'Zoltán Kovács',
'Gabriel Sobota',
'Jozef  Uram',
'Juraj Kis',
'Michal Flešár',
'Juraj Kürthy',
'Ľudovít Iván',
'Zdenko Čambal',
'Karol Ferencz',
'Jana Tureková',
'Robert Hlaváč',
'Karol Pilinský',
'Rudolf Gabryš',
'Jozef Nemec',
'Dana Kohútová',
'Jozef Gálus',
'Ján Varga',
'Tibor Mičko',
'Emil Rábek',
'Ľuboš Hačko',
'Vladimír Bušniak',
'Miroslav Hamar',
'Ivan Lenár',
'Milan Staňo',
'Tivadar  Sidó',
'Edita Moravská',
'Ľubomír Krajňanský',
'Jana Kukučková',
'Juraj Ondračka',
'Ondrej Piški',
'Jozef Hrotek',
'Simona Holicová',
'Alena Bugárová',
'Stanislav Jurák',
'Ján Hrčka',
'Milan Mokrý',
'Jozef Ladický',
'Martin Cibula',
'Erika Korčoková',
'Andrej Puss',
'Jozef Hedera',
'Marián Beneš',
'Jarmila Petrovičová',
'Eva Kukučková',
'Ladislav Nozdrovický',
'Ivan Dobrota',
'Pavol Dobosy',
'Tomáš Pásztor',
'Jozef Húserka',
'Richard Kurec',
'Martin Fulka',
'Tibor Veľký',
'Peter Varga',
'Pavol Foltán',
'Zuzana Vysokaiová',
'Viera Darivčaková',
'Mária Hnilicová',
'Štefan Bodó',
'Dušan Ďuríček',
'Stanislav Rohoň',
'Andrej Torda',
'Ľudovít Húdik',
'Ján Kľuka',
'Miroslav Káčerík',
'Milan Velas',
'Erik Timko',
'Ľuboš Karel',
'František Rácz',
'Peter Štepianský',
'Viera Sakálová',
'Miroslav Brath',
'Silvia Kukučková',
'Tibor Béres',
'Peter Čopák',
'Jozef Pavligovský',
'Helena Mihalčinová',
'Eva Sevaldová',
'Erika Mojáková',
'Ján Adámik',
'Jaroslav Hovančák',
'Darina Labaničová',
'Sergej Vasilenko',
'Jozef Maxin',
'Anton Kulan',
'Eva Mráziková',
'Ján Kolcun',
'Jana Skokanová',
'Stanislava Kellnerová',
'Miloš Baránik',
'Nataša Iskrová',
'Lukáš Piroha',
'Rastislav Beňo',
'Ivan Kolník',
'Ondrej Knechta',
'Miriam Sabovčiková',
'Miroslav Pokrivčák',
'Vladimír Horváth',
'Pavel Hučko',
'Renáta Demková',
'Rudolf Balog',
'Ladislav Tankó',
'Ján Vincenčík',
'Jarmila Dobroňová',
'Stanislav Horník',
'Milan Michlík',
'Gejza Nagy',
'Slavomír Poliak',
'Jaroslav Kráľovič',
'Ján Melicher',
'Branislav Nociar',
'Marian Mazúch',
'Maroš Kočiš',
'Bohuslav Nemky',
'Róbert Csudai',
'Miroslav Ostrihoň',
'Igor Kanda',
'Jozef Brhlík',
'Jozef Chudý',
'Jozef Seneši',
'Ľubomír Krovina',
'Ján Klačko',
'Vladimír Fabo',
'Štefan Trusák',
'Adrián Takács',
'Pavel Bendík',
'Gabriel Parti',
'Jozef Benca',
'Ján Sklenár',
'František Škapec',
'Mária Horváthová',
'Jana Myjavcová',
'Katarína Škvarlová',
'Stanislav Nechaj',
'Gabriel Gencsi',
'Jaroslav Horváth',
'Martina Bodnárová',
'Pavol Guláš',
'Miloš Meričko',
'Peter Majerčák',
'Mikuláš Horvát',
'Ľubomír Petrák',
'Peter Závodský',
'Michal Copák',
'Peter Fazekaš',
'Mária Semaníková',
'Juraj Staš',
'Marek Lackovič',
'Martin Šimún',
'Karol Pavlíček',
'Júlia Kočíková',
'Ludevít Czókoly',
'Gregor Izrael',
'Anton Staš',
'Cyril Hirjak',
'Zita Pleštinská',
'Juraj Gáll',
'Mária Krušková',
'Ján Jakab',
'Cyril Miškuf',
'Peter Konečný',
'Jozef Červeňák',
'Alena Záhoreczová',
'Ľubomír Škriečka',
'Radoslav Hvožďak',
'Vladimíra Vydrová',
'Karol Köteleš',
'Vladimír Čač',
'František Magyari',
'Jana Šupová',
'Marta Benedeková',
'Ondrej Mihňák',
'Jozef Varga',
'Štefan Hudáček',
'Tibor Čičmanec',
'Renáta Zdražilová',
'Ján Belov',
'Ján Horváth',
'Milan Daniš',
'Vladimír Vaculčiak',
'Marian Kollár',
'Branislav Dobrotka',
'Mária Lachkovičová',
'Peter Medvec',
'Peter Holek',
'Ján Turek',
'Ján Kubík',
'Viktor Wiedermann',
'Anna Frankovičová',
'Vratislav Cengel',
'František Tyukos',
'Jozef Rosipal',
'Ľubomír Macko',
'Ján Chrapovič',
'Viktor Lestyánszky',
'Magdalena Tóthová',
'Arnold Ozsvald',
'Lýdia Fačková',
'Vladimír Guoth',
'Róbert Kleskeň',
'Tibor Balyo',
'Martin Šaulič',
'Jana Maršálková',
'Mária Hládeková',
'István Domin',
'Karol Kováč',
'Štefan Šipoš',
'Vladimír Koscelnik',
'Slavomír Pocisk',
'Silvester Nestarec',
'Anna Cigáneková',
'Jozef Molčan',
'Slavomír Zubriczky',
'Igor Hindi',
'Ondrej Uhliarik',
'Ladislav Čička',
'Jaroslav Božik',
'Jarmila Csiba',
'Matúš Fedor',
'Ľubor Seman',
'Jozef Mačuga',
'Peter Gajdár',
'Magdaléna Sasaráková',
'Milan Zuzaniak',
'Martin Kollár',
'Ján Smetanka',
'Radoslav Michalčin',
'Peter Kotian',
'Marián Paulovič',
'Adriana Vicianová',
'Alena Vlčková',
'František Pavol',
'Marta Martinovicsová',
'Július Begala',
'Lajos Berner',
'Jaroslav Vasiľ',
'František Harčár',
'Božena Kováčová',
'Ľubomír Kundrát',
'Jozef Čechovič',
'Jozef Kacvinský',
'Marián Žec',
'Juraj Pružinec',
'Lívia Kovalčíková',
'Stanislav Sťahel',
'Florián Giňa',
'Richard Pekar',
'Marek Kordík',
'Lucia Sukeľová',
'Michal Šabak',
'Rajmund Bradík',
'Ladislav Trybula',
'Martin Mikolka',
'Ján Škorvánek',
'Božena Krajčovičová',
'Marián Dzurik',
'Ladislav Polák',
'Zdenko Matúška',
'Michal Džuka',
'Ján Ždiňak',
'Adriana Matúšeková',
'Ivan Gejdoš',
'Anna Guzyová',
'Dušan Kazimír',
'Ivan Varga',
'Gabriel Kiš',
'Milan Kolesár',
'Ladislav Hroššo',
'Viera Sárová',
'Jaroslav André',
'Eva Mozoličová',
'Gabriel Mihályi',
'Katarína Zagyiová',
'Pavel Greguš',
'Milan Krempaský',
'Ildikó Lukacsová',
'Ľubica Čornejová',
'Jozef Kovács',
'Gabriel Fekete',
'Zuzana Molčanyová',
'Jozef Lukačin',
'Michal Tomko',
'Lívia Farkasová',
'Martina Mračková',
'Július Česák',
'Jozef Rabatin',
'Jozef Konrád',
'Ivan Sivák',
'Ján Šárkan',
'Ladislav Éhn',
'Ladislav Hakulin',
'Iveta Poluchová',
'Jozef Cauner',
'Réka Papp',
'Vojtech Váradi',
'Gabriela Ivaňáková',
'Jana Macejková',
'Peter Hudec',
'Erik Vranka',
'Dušan Ďuriš',
'Michal Guľaš',
'Monika Hamaďaková',
'Ján Elzer',
'Igor Daško',
'Dezider Pataki',
'Jozef Grman',
'Pavol Sandanus',
'Zdenko Gaďo',
'Ladislav Pixiades',
'Katarína Heiszlerová',
'Benjamín Blaha',
'Juraj Jedinák',
'Ivor Husár',
'Margita Tabačeková',
'Pavol Fek',
'Vladimír Vittek',
'Slávka Guteková',
'Tibor Varga',
'Adriana Malatová',
'Anton Hodor',
'Róbert Katuš',
'Pavol Johanes',
'Ivana Chrenková',
'Tomáš Toma',
'Miroslav Galas-Zaufal',
'Emil Ondrík',
'Jana Feňová',
'Július Lőrincz',
'Jozef Konkoly',
'Igor Kočiško',
'Aladár Szajkó',
'Attila Farkas',
'Ján Ferenčák',
'Pavol Suchánsky',
'Emília Cvíčelová',
'Jozef Jánošík',
'Jozef Ďuriš',
'Daniel Lorinc',
'Ľuboš Haring',
'Ján Balázs',
'Erika Cintulová',
'Iveta Randziaková',
'Miroslav Fabian',
'Helena Csákyová',
'Kamila Bogdaňová',
'Slavomil Voloch',
'Zlata Kaštanová',
'Rastislav Bačík',
'Karol Revaj',
'Štefan Čoros',
'Rozália Szalay',
'Radoslav Hruška',
'Jana Foldinová',
'Monika Hudáčková',
'Božena Poliačková',
'Csaba Bognár',
'Štefan Kováč',
'Jozef Valko',
'Jozef Sádovský',
'Janka Regrutová',
'František Vojček',
'Jozef Šoltys',
'Peter Vojtko',
'Tatiana Klimová',
'Vojtech Čičmanec',
'Štefan Lányi',
'Monika Kopúnová',
'Jana Lazoriková',
'Katarína Lászlóová',
'Anton Aštary',
'Anton Bašniar',
'Ján Chromek',
'Miroslav Skička',
'Mikuláš Hudák',
'Pavol Zamiška',
'Lýdia Petríková',
'Renáta Poboriová',
'Jozef Hruštinec',
'Árpád Horváth',
'Jana Sidorová',
'Marek Antoš',
'Mária Pokrivňáková',
'Róbert Balkó',
'Jitka Puhallová',
'Matúš Leňo',
'Ľubor Krnčan',
'Jana Kráľová',
'Béla Keszegh',
'Jozef Bednár',
'Marián Bužický',
'Peter Hlavatý',
'Otto Brtko',
'Imrich Lukács',
'Miroslav Konštiak',
'Tivadar Karkus',
'Miroslav Kamhal',
'Janka Stupňanová',
'Kvetoslava Šabáková',
'Dušan Dubecký',
'Rastislav Slanina',
'Jozef Števik',
'Peter Krupa',
'Ján Záchenský',
'Jaroslav Kapa',
'Marianna Bebčáková',
'Silvia Žeňuchová',
'Mária Dudiňaková',
'Dušan Mitter',
'Peter Palenčár',
'Eva Gyurászová',
'Silvia Kosíková',
'Peter Hric',
'Anton Medvec',
'Mária Segíňová',
'Miroslav Michalík',
'Hubert Danihel',
'Peter Pilko',
'Igor Šillo',
'Mária Žofčinová',
'Miroslav Cibulka',
'Ladislav Gódány',
'Peter Závadinka',
'Štefan Antol',
'Peter Čokota',
'Radomír Brtáň',
'Rastislav Čepák',
'Jaroslav Polaček',
'František Krištof',
'Jozef Andrejčák',
'Adriana Šebeščáková Balogová',
'Jaroslav Hlinka',
'Martin Balčík',
'Michal Krcho',
'Peter Tomko',
'Damián Exner',
'Marcel Šaňa',
'Iveta Šimková',
'Lenka Kovačevičová',
'Jozef Karabin',
'Ladislav Brada',
'František Ténai',
'Ladislav Lörinc',
'Miloš Ihnát',
'Igor Petrovčik',
'Daniel Petrík',
'Monika Puzderová',
'Ján Nigut',
'Viktor Mikluš',
'Marcel Vrchota',
'Jozef Petkač',
'Marta Petrilová',
'Slavomír Horváth',
'Michal Kmec',
'Vladimír Babič',
'Martin Halaksa',
'Marián Bunganič',
'Zdenka Mačicová',
'Peter Mozolík',
'Mária Oravcová',
'Jozef Žabka',
'Ján Izrael',
'Adrián Dáni',
'Jozef Filip',
'Pavol Kuba',
'Patrik Renováček',
'Andrej Čopík',
'Bystrík Ižold',
'Eva Petáková',
'Peter Čižmár',
'Peter Rajnič',
'Gejza Köver',
'Ján Zajac',
'František Mašlej',
'Miroslav Schwarz',
'Ján Štefanco',
'Jozef Feciľak',
'Helena Babejová',
'Ján Konečník',
'Ján Vaňko',
'František Klinovský',
'František Béres',
'Ivan Škamla',
'Gergely Agócs',
'Vladimír Kapríni',
'Ferenc Bergendi',
'Dušan Šebok',
'Ľuboš Palovič',
'Radoslav Šimko',
'Ľubomír Slančík',
'Zoltán Wurczell',
'Karol Pataky',
'Ján Blaho',
'Marko Osif',
'Milan Došek',
'Jana Žáková',
'Martin Mikloš',
'Jozef Grapa',
'Gabriel Klárik',
'Peter Bollo',
'Tibor Kostovčík',
'Vladimír Bajaj',
'Igor Gavalier',
'Jaroslav Capko',
'Gabriel Duka',
'Darina Palaiová',
'Silvia Bukovičová',
'Alexander Ferenčík',
'Juraj  Vozár',
'Anna Janošová',
'Monika Dovičaková',
'Július Tamaška',
'Juraj Leginus',
'Imrich Paľko',
'Ján Šejirman',
'Ján Steranka',
'Mária Prekopová',
'Richard Kubáň',
'Oľga Dutková',
'Jozef Grivalský',
'Cyril Harničár',
'Svetlana Královičová',
'Drahomíra Hricová',
'Ľuboš Meluš',
'Lukáš Remper',
'Iveta Rušinová',
'Jaroslav Kráľ',
'Peter Kováčik',
'Juraj Oravec',
'Anna Kertisová',
'Radoslav Vazan',
'Terézia Pacoňová',
'Viktor Bochin',
'Martin Zdychavský',
'Jozef Kmec',
'Adrián Gužo',
'Ondrej Lipták',
'Pavel Černák',
'Tatiana Botková',
'Zsolt Német',
'Vincent Breznický',
'Michal Mantič',
'Róbert Bujna',
'Dušan Hric',
'Štefan Kožlej',
'Ľuba Tóthová',
'Monika Kavecká',
'Peter Slašťan',
'Eva Gyenesová',
'Dušan Mésároš',
'Ján Bartoš',
'Martin Faltin',
'Ján Božík',
'Mária Špirková',
'Vladimír Jus',
'František Bokros',
'Branislav Vávra',
'Peter Mojžiš',
'Martin Vincej',
'Jozef Grúň',
'Pavol Veteráni',
'Radovan Kapraľ',
'Marián Pavlík',
'Zoltán Sojka',
'Slavomír Kujan',
'Milan Dirga',
'Martina Kubišová',
'Ľubomír Krajňák',
'Erika Orosz Ágošton',
'Helena Borčíková',
'Marián Mihalda',
'Milan Králik',
'Marián Moravčík',
'Andrea Parobková',
'Marek Gallík',
'Ľuboslava Hofericová',
'Ján Katica',
'Jaroslav  Koyš ',
'Alžbeta Patayová',
'Michal Magura',
'Vladimír Baran',
'Miroslav Kacarabčin',
'Vladislav Cuper',
'Miloš Čmela',
'Oľga Procházková',
'Vladimír Kostár',
'Lenka Janíková',
'Ľubomír Šipoš',
'Lukáš Hrinko',
'Marek Miker',
'Mário Kubiš',
'Jana Matiašková',
'Ján Mičega',
'Peter Nazarej',
'Kamil Karas',
'Marian Horečný',
'Martin Krompaský',
'František Szitási',
'Radoslav Kriváček',
'Ivan Antal',
'Ján Daňo',
'Richard Laššan',
'Juraj Zaťko',
'Jozef Musala',
'Milan Őrmezey',
'Alexander Mezei',
'Michal Zurbola',
'Marko Bučko',
'Jana Bľandová',
'Ján Rákoši',
'Pavel Hudáček',
'Marián Habovčík',
'Dušan Sudár',
'Terézia Kavuliaková',
'Ladislav Majdán',
'Martin Blihár',
'Peter Bobík',
'Ján Gondek',
'Miroslav Kovalčík',
'Slavomír Zahornadský',
'Marián Dvorský',
'Marta Halászová',
'Ján Krtík',
'Kristína Cselényiová',
'Miroslav Vilkovský',
'Katarína Michálková',
'Ingrid Sitárová',
'Ladislav Miklóš',
'Mária Ščepitová',
'Martin Dreveňák',
'Pavel Haško',
'Michal Turay',
'Marta Salanciová',
'Zdenka Judáková',
'Ľubomír Noska',
'Pavol Gašpierik',
'Marian Sliviak',
'Vladimír Jamečný',
'Marián Javorka',
'Adriana Čechovičová',
'Vladimír Jánošík',
'Peter Mikuško',
'Ľubomír Pankuch',
'Tatiana Ölvecká',
'Dušan Čura',
'Vladimír Kumštár',
'Ján Šatník',
'Dáša Kovácsová',
'Jozef Mada',
'Janka Mičudová',
'Dušan Turčan',
'Robert Emödi',
'Ivan Bella',
'Július Porubän',
'Albín Husarčík',
'Róbert Kuzma',
'Jana Gazdičová',
'Igor Guráň',
'Dušan Lauko',
'Milan Kašák',
'Slavomír Kopáč',
'Jozef Malý',
'Ján Hollý',
'Ján Jaňák',
'Jana Šimová',
'Milan Frič',
'Branislav Tréger',
'Juraj Filo',
'Elena Tuková',
'Ján Blcháč',
'Ľuboš Žubor',
'Anna Papajová',
'Karol Maťko',
'Jozef Murina',
'Marián Školník',
'Ľubica Tuhárska',
'Nataša Hlinková',
'Jana Petrejeová',
'Alena Kubrická',
'Jaroslav Stracenský',
'Helena Frandoferová',
'Alžbeta Suriaková',
'Ján Márföldi',
'Miroslav Valčičák',
'Jozef Katreniak',
'Jozef Krestaň',
'Ľudmila Hospodárová',
'Mária Oračková',
'Karol Konczi',
'Marián Bederka',
'František Palko',
'Peter Harcek',
'Juraj Rábara',
'František Richter',
'Ondrej Bahno',
'Štefan Horvát',
'Marian Lenhard',
'Ľuboš Tvrdoň',
'Monika Pastírová',
'Silvia Esztergályosová',
'Erik Gemzický',
'Milan Pavko',
'Ján Kapolka',
'Pavel Zajac',
'Martin Beňatinský',
'Jozef Sklenčár',
'Peter Dávidík',
'Marcel Šupica',
'Ján Žilka',
'Miroslav Makara',
'Jozef Havrila',
'Jozefína Štofanová',
'Ladislav Kiss',
'Pavel Kováč',
'Alexandra Pivková',
'Martina Jenčová',
'Monika Kičáková',
'Ľuboš Tatranský',
'Vladimír Murcko',
'Mikuláš Mašlej',
'Jozef Szabó',
'Branislav Hrbček',
'Vladimír Závadský',
'Eduard Baláž',
'Ivan Michna',
'Matúš Dočkalik',
'Renáta Kováčová',
'Peter Slimák',
'Mária Sedláčeková',
'Marian Haluza',
'Martin Meričko',
'Igor Cok',
'Michal Bartko',
'Andrej Kotuľa',
'Jozefína Kramárová',
'Alena Segedyová',
'Ján Behro',
'Mária Farkašová',
'Peter Tejiščák',
'Ján Pružina',
'Vladimír Lelovský',
'Anton Štefko',
'Marian Korbel',
'Juraj Halás',
'Miroslav Čorba',
'Jozef Bojda',
'Michal Ondrička',
'Michal Šmehýl',
'Ľudmila Láníková',
'Gabriel László',
'Alena Jelušová',
'Milan Pršebica',
'Bohumil Bielik',
'Tibor Marek',
'Ján Sarvaš',
'Martin Pavlík',
'Ján Ďuk',
'Ján Šimko',
'Jozef Krpelan',
'Jaroslav Koleda',
'Jaroslav Makatúra',
'Milan Kalafut',
'Mária Jandáková',
'Jana Kallová',
'Dušan Pacalaj',
'Adriána Fečková',
'František Hontvári',
'Rita Pásztorová',
'Anna Bandiová',
'Jozef Drigan',
'Juraj Říha',
'Lucia Ferenc Gajdúšková',
'Karol Streda',
'Zdenko Kubáň',
'Jaroslav Podhorány',
'Miroslav Cingeľ',
'Monika Hamzová',
'Miroslav Kováč',
'Zoltán Marczell',
'Marta Gregorová',
'Eva Belančíková',
'Attila Pszár',
'Ladislav Pisch',
'Eva Mešinová',
'Ján Hamar',
'Adrian Pernecký',
'Beáta Csenger',
'Milan Dolák',
'Jolana Žeňuchová',
'Pavol Gubáň',
'Tatiana Káššayová',
'Csilla Bálintová',
'Štefan Čepko',
'Jana Ďurčeková',
'Veronika Kubíková',
'Jozef Filkus',
'Igor Lacko',
'Juraj Stiffel',
'Eugen Janík',
'Břetislav Chytil',
'Leonidas Charizopulos',
'Miroslava Sumková',
'Csaba Furik',
'Ágnes Máté',
'Václav Hájevský',
'Peter Švec',
'Jozef Šesták',
'Ladislav Oravec',
'Jozef Javorský',
'Stanislav Mathia',
'Miroslav Macko',
'Igor Sádovský',
'Milan Vrábel',
'Ervin Varga',
'Igor Petrik',
'Jozef Kuziak',
'Dušan Statelov',
'Valéria Eľková',
'Ondrej Lipták',
'Marek Virág',
'Andrea Butková',
'Ján Danko',
'Slavomír Fabian',
'Juraj Bobek',
'Eugen Radič',
'István Keszeg',
'Bronislava Brablecová',
'Emil Jasik',
'Marta Stanislavová',
'Monika Husivargová',
'Marián Štefaňák',
'Lukáš Suchanič',
'Lýdia Czapová',
'Marta Mészárosová',
'Pavol Pastirčák',
'Pavel Plachý',
'Juraj Červák',
'Ladislav Kulacs',
'Jozef Kipikaša',
'Matej Smorada',
'Michal Baran',
'Pavol Svetlík',
'Michal Janota',
'Vladislav Višňovský',
'Katarína Remencová',
'Ján Ferus',
'Csaba Husaník',
'Ján Šoltis',
'Stanislav Michal',
'Milan Madura',
'Ján Hlinka',
'Stanislav Baka',
'Pavel Andrijko',
'Katarína Janikovicsová',
'Juraj Trgyňa',
'Jana Glogovská',
'Július Borbély',
'Peter Porubský',
'Zoltán Tarbaj',
'Viera Mihočová',
'Terézia Tisovčíková',
'Viliam Zahorčák',
'Mária Čuchtová',
'Dušan Džula',
'Peter Rusiňák',
'Eva Holbová',
'Imrich Ágošton',
'Štefan Nagy',
'Milan Baďanský',
'Ladislav Rabatin',
'Miroslav Mojsej',
'Marián Engel',
'Michal Kurečko',
'Miroslav Čičmanec',
'Peter Kidala',
'Milena Svocáková',
'Július Vachmanský',
'Iveta Geletková',
'Jozef Kováč',
'Ľudovít Kujnisch',
'Peter Žemba',
'Eszter Tóth',
'Roman Urbánik',
'Adriana Vančová',
'Juraj Petrakovič',
'Ondrej Milčo',
'Štefan Édes',
'Stanislav Uhrin',
'Vladimír Balaj',
'Mária Bednárová',
'Martin Palka',
'Štefan Svetko',
'František Staňo',
'Jozef Čunderlík',
'Július Laššan',
'Mária Lacková',
'Marián Beňa',
'Peter Pobuda',
'Slavomír Borovský',
'Vladimír Čeklovský',
'Peter Hulman',
'Róbert Palko',
'Anton Emrich',
'František Mastný',
'Tibor Rózsár',
'Elena Krajčová',
'Katarína Chabanová',
'Ondrej Chlebuš',
'Martin Mach',
'Maroš Lacko',
'Ján Kluka',
'Pavol Polaščik',
'Zoltán Benkő',
'Ľubomír Maťko',
'Iveta Horvathová',
'Vojtech Nagy',
'Roman Goldschmidt',
'Ján Kvetko',
'Marian Szentandrassi',
'Miloslav Marčák',
'Jaroslav Oravec',
'Marián Murín',
'Iván Farkas',
'Pavel Halabrín',
'Helena Podolinská',
'Dana Marková',
'Štefan Mojzeš',
'Roman Švantner',
'Anton Šandor',
'Július Paulička',
'Vladimír Roháč',
'David Ivanovič',
'Ondrej Klekner',
'Milan Hubík',
'Dezider Molnár',
'Marian Laciak',
'Jozef Lukács',
'Peter Majko',
'Jozef Jakubík',
'Elena Magdolenová',
'Henrieta Selmecziová',
'Peter Vajda',
'Jaroslav Pekár',
'Vladimír Megela',
'Alena Samuelčíková',
'Ján Paľa',
'Jozef Pavuk',
'Jozef Mokoš',
'Jozef Keseg',
'Branislav Čižmárik',
'Viera Uhlárová',
'Mária Gallovičová',
'Miloš Mojto',
'Ladislav Híves',
'Ján Haninec',
'Jozef Madarász',
'Zuzana Jancová',
'Zoltán Molnár',
'Milan Kováč',
'Beata Vrecková',
'Kristína Bónová',
'Štefan Henžel',
'Adriana Vraňanová Kubičková',
'Ladislav Ďureček',
'Marek Hattas',
'Tivadar Berky',
'Michal Toman',
'Mária Majtánová',
'Katarína Nagyová',
'Andrej Richter',
'Robert Štrbák',
'Pavol Caňo',
'Miroslav Jemala',
'Kamil Mikuš',
'Jaroslav Rosina',
'Silvia Skusilová',
'Iveta Vasilenková',
'Martina Kucerová',
'Alena Džupinová',
'Miroslav Líška',
'Miroslav Sisák',
'Igor Madzin',
'Martin Močilenko',
'Ján Cundra',
'Magdaléna Ohradzanská',
'Stanislav Rakár',
'Tibor Jerga',
'Marcel Kaščák',
'Ján Hudák',
'Marta Vrabľová',
'Jozef Abrahamovský',
'Monika Obšitošová',
'Marcela Pčolinská',
'Ján Fenčák',
'Gabriela Staníková',
'Jana Leščišinová',
'Ján Čaraba',
'Július Kovács',
'Anna Hrešková',
'Juraj Petný',
'Miroslav Bystriansky',
'Jozef Kamenický',
'Dana Karnišová',
'Ján Garbár',
'Vladimír Mihalik',
'Peter Doval',
'Branislav Jaďuď',
'Richard Molnár',
'Ján Žucha',
'Jozef Balačin',
'Pavol Novák',
'Zuzana Árvová',
'Peter Marušinec',
'Mária Telepunová',
'Peter Hritz',
'Júlia Boďová',
'Anton Šimčák',
'Ján Barvirčák',
'Vasiľ Dinič',
'Štefan Paholík',
'Igor Jambor',
'Mária Korčoková',
'Valéria Geri',
'Ján Štrbík',
'Dušan Šimka',
'Alena Spodniaková',
'Jozef Trstenský',
'Silvia Halvoníková',
'Otokar Klein',
'Jozef Jastrab',
'Radoslav Kozák',
'Ján Borovský',
'Andrea Michalková',
'Zuzana Pavleová',
'Ladislav Nagy',
'Tibor Fehér',
'Zoltán Fekete',
'Miloš Koči',
'Monika Vajda',
'Mária Baboľová',
'Arpád Csuri',
'Danka Uhrinková',
'Milan Garaj',
'Miroslav Beňovič',
'Ján Senko',
'Mária Goduľová',
'Anikó Rabay',
'Andrea Kličová',
'Radoslav Ďuroška',
'Július Rusnák',
'Ladislav Polák',
'Iveta Feketeová',
'Martin Jech',
'Vladimír Magač',
'Jaroslav Salaj',
'Ildikó Gyurcsiová',
'Imrich Drutarovský',
'Štefan Cudrák',
'Vladimír Ščerba',
'Jozef Vízi',
'Slavomír Havír',
'Mikuláš Demočko',
'Ján Biroš',
'Jozef Klešč',
'Ján Kundrát',
'Karol Pinčák',
'František Marcin',
'Alojz Marček',
'Martin Mika',
'Ivana Frívaldská',
'Jozef Lopuchovský',
'Jozef Bielokostolský',
'Martin Müller',
'Iveta Mondeková',
'Dana Melišková',
'Csaba Kálazy',
'Ján Krnáč',
'Imrich Taiš',
'Peter Bartovič',
'Milan Gál',
'Anna Filipčová',
'Ján Lichanec',
'Karol Graňák',
'Marek Majdiš',
'Michal Strnál',
'Vladimír Kubišta',
'Albín Maslaňák',
'Jozef Hamaň',
'Jozef Záhora',
'Andrea Mlynarčíková',
'Rastislav Repka',
'Szilárd Gálffy',
'Tomáš Mikuš',
'Agnesa Stričková',
'Róbert Kopáčik',
'Peter Timočko',
'Katarína Forgáčová',
'Ján Čisár',
'Miroslav Jurák',
'Róbert Mikuláško',
'Jozef Kvokačka',
'František Priekala',
'Peter Siman',
'Juraj Jelok',
'Stanislav Margolien',
'Jozef Tkácz',
'František Marcin',
'Rastislav Popuša',
'Július Remenár',
'Kristína Gregoričková',
'Anton Fiala',
'Marián Plevko',
'Ján Strempek',
'Vojtech Šomošvári',
'Ervín Schmieger',
'Eduard Jenča',
'Pavel Salva',
'Ján Matej',
'Ladislav Zagiba',
'Zoltán Szabó',
'Peter Polóni',
'Jozef Fedorko',
'Ľubica Karasová',
'Tibor Tomko',
'Vasiľ Bomberovič',
'Milan Korenči',
'Atilla Papp',
'Rozália Juhászová',
'Miroslav Lukáč',
'Roman Španihel',
'Juraj Guzej',
'Ján Stanko',
'Ján Hančiak',
'Ladislav Balážec',
'Jozef Božik',
'Oto Mészáros',
'Daniel Tejkal',
'Roman Viola',
'Ján Masný',
'Jozef Berčík',
'Ernest Takács',
'Rozália Tóthová',
'Viliam Kupčo',
'Mária Komarová',
'Ivana Stachová',
'Monika Górová',
'Rudolf Tomko',
'Vojtech Menyhárt',
'Jozef Kočiš',
'Anton Kocela',
'Mária Gendiarová',
'Michal Grňa',
'Ladislav Boháčik',
'Jozef Lukniš',
'Štefan Valko',
'Jaroslav Dujava',
'Jozef Holečko',
'Ladislav Molnár',
'Martin Ledník',
'Mária Vadasová',
'Anna Hrúzová',
'Radko Rožánek',
'Štefan Beňa',
'Ján Lenko',
'Gyula Köböl',
'Ján Jenčo',
'Pavel Tomčo',
'Štefan Rovňák',
'Anton Pláňavský',
'Ján Dovec',
'Igor Hianik',
'Peter Jančovič',
'Július Baník',
'Radovan Mičunek',
'Ľubomír Aláč',
'Eugen Čižmárik',
'Valéria Votoupalová',
'Ján Kočiš',
'Magdaléna Šatníková',
'Martina Záhorcová',
'Peter Köpöncei',
'Kornélia  Sádovská',
'Július Papán',
'Peter Válek',
'Jozefína Bartoňová',
'Radoslav Benkovič',
'Peter Šlosár',
'Rastislav Grich',
'Peter Koščo',
'Miroslav Plaucha',
'Iveta Šušánová',
'Miroslav Kremeň',
'Štefan Sýkora',
'Eva Bakošová',
'František Petro',
'Martin Lednický',
'Ladislav Lagín',
'Dušan Triebušník',
'Slavomír Korčuška',
'Milan Kadlíček',
'Ladislav Kardhordó',
'Roman Ivan',
'Magdaléna Bogyová',
'Jozef Oračko',
'Ľubica Potocká',
'Anton Chobot',
'Dana Lóžiová',
'Anton Hricko',
'Ľudovít Michalovič',
'Milan Štefkovič',
'Bohuslav Bella',
'Katarína Pošiváková',
'Ivan Barla',
'Jozef Malatinec',
'Ján Morihladko',
'Pavel Miksa',
'Ida Kováčová',
'Rastislav Bobocký',
'Jaroslav Seman',
'Peter Kulich',
'Zuzana Dočekalová',
'Marián Vojtík',
'Ján Opial',
'Mária Hrčková',
'Jana Tkáčiková',
'Laura Prešinská',
'Dušan Nepšinský',
'Igor Šagát',
'Ľudovít Nagy',
'Mária Štrbáková',
'Miroslav Lupták',
'Jozef Kaľavský',
'Mikuláš Csorba',
'Jaroslav Tvardzik',
'Pavol Kňazský',
'Pavel Kyseľ',
'Ján Punka',
'Ľubica Poluchová',
'Pavol Hanušovský',
'Ján Lihan',
'Martina Brisudová',
'Martin Šujan',
'Mária Matlochová',
'Jana Ondrejková',
'Anton Danko',
'Ľubor Kvaka',
'Iveta Komorová Hiľovská',
'Dana Žúrková',
'Peter Volčko',
'Martin Pražienka',
'Miroslav Hreščák',
'Tomáš Tóth',
'Juraj Kriška',
'Igor Frko',
'Martina Stašová',
'Andrea Raková',
'Gabriel Falis',
'Tadeáš Malý',
'Katarína Machová',
'Martin Kurek',
'Milan Vavrek',
'Dušan Šmajda',
'Leonard Flaška',
'Peter Kučík',
'Eva Ninisová',
'Karol Janas',
'Alena Dudeková',
'Alexander Csóka',
'Ivona Patrášová',
'Katarína Ivaničová',
'Ján Čižmárik',
'Miroslav Činčura',
'Erik Marčok',
'Martin Czebrik',
'Erika Nemešová',
'Emil Škodáček',
'Róbert Mikulášik',
'Ján Debnár',
'Viera Graňačková',
'Dušan Macho',
'Anton Lagíň',
'Tatiana Čontofalská',
'Štefan Klus',
'Alena Ciglanová',
'Juraj Trsťan',
'Ján Abrahám',
'Andrea Turčanová',
'Tibor Čierny',
'Ernest Fedor',
'Norbert Zsitva',
'Rastislav Suroviak',
'Erika Vrabcová',
'Milan Kohút',
'Stanislav Chaban',
'Peter Sekerák',
'Peter Czere',
'Dana Blažková',
'Peter Flamík',
'Tatiana Beňáková',
'Katarína Macháčková',
'Milan Čipka',
'Miroslav Goldir',
'Jozef Blaško',
'Jozef Sivák',
'Ján Pavuk',
'Martina Rozenbergová',
'Martin Digoň',
'Peter Hamráček',
'Gábor Nagy',
'Viliam Cíbik',
'Igor Súkeník',
'Michal Ušiak',
'Anna Mihalíková',
'Martin Dzemján',
'Alexander Takács',
'Metod Sojčák',
'Katarína Heneková',
'Ján Rievaj',
'Juraj Jevin',
'Ondrej Andraščík',
'Tomáš Nemeček',
'Henrich Čambál',
'Ján Namešpetra',
'Július Piták',
'Jozef Slovík',
'Mária Mozsárová',
'Gabriela Viazanková',
'Marian Chrenko',
'Kristína Biskupičová',
'Aladár Bari',
'Elena Valenteje',
'Anton Tkáčik',
'Daniela Zelonkayová',
'Marta Kolková',
'Vladimír Kočárik',
'Miroslav Remenár',
'Jaroslav Fekula',
'Ľubomír Púchovský',
'Jana Svičinová',
'Ľudmila Kerestešová',
'Péter György',
'Božena Dubasová',
'Mária Švecová',
'Milan Lipka',
'Miloš Mikula',
'Katarína Hollá',
'Lýdia Nemogová Gallová',
'Igor Antoni',
'Anton Heglas',
'Iveta Horvatová',
'Peter Olejník',
'Dušan Daloš',
'Ľuboš Lešták',
'Patrik Antal',
'Eva Gajdicová',
'Lenka Fedáková',
'Ján Rencsok',
'Stanislav Hada',
'Ladislav Sóky',
'Marek Rakoš',
'Miroslav Juhász',
'Aladár Miklós',
'Milan Spodniak',
'Ján Bobrovský',
'Martin Červenka',
'Rastislav Frkáň',
'Milan Koska',
'Stanislav Palic',
'Dušan Bodnár',
'Daniela Sigetová',
'Monika Juneková',
'Ivan Škrteľ',
'Zuzana Vaníková',
'Radovan Rokošný',
'Zoltán Metzner',
'Dárius Kuruc',
'Slávka Krišťáková',
'František Dudžák',
'Jaroslav Pasternák',
'Marek Kondžura',
'Miroslav Paločko',
'Peter Cipka',
'Vladimír Šalkovský',
'František Bodnár',
'Helena Jamroškovičová',
'Július Buchta',
'Ján Šeševička',
'Marián Spišiak',
'Oskár Tóth',
'Ivan Dunka',
'Zuzana Germanová',
'Elena Polóniová',
'Márta Stubendek',
'Jozef Šimko',
'Marián Šivara',
'Stanislav Krahulec',
'Milan Medveď',
'Mário Machovec',
'Roman Ravas',
'Zoltán László',
'Peter Švaral',
'Jana Paľová',
'Stanislav Levrinc',
'Miloš Jaš',
'Ľubomír Pangrác-Piter',
'Jozef Drobňák',
'Viera Palejová',
'Jozef Machyna',
'Milan Čeremeta',
'Andrej Lalik',
'Marian Rehuš',
'Milan Kubeš',
'Jana Cabanová',
'Jaroslava Ďurove',
'Jozef Baláž',
'Stanislav Viravec',
'Viktor Gazdačko',
'Viktor Vápeník',
'Martin Jurkovič',
'Beáta Kollárová',
'Michal Domik',
'Želmíra Gonosová',
'Štěpánka  Zacharová',
'Anna Mičianová',
'Viliam Michel',
'Jozef Švirík',
'Juraj Vasiľ',
'Henrieta Horváthová',
'Rastislav Neuvirth',
'Ivan Javorček',
'Monika Malcová',
'Oľga Kormošová',
'Zdena Lichnerová',
'Marián Šurjanský',
'Jozef Jankovič',
'Jozef Hibler',
'Marián Regula',
'Erika Lakatošová',
'Ján Sakulič',
'Anna Kuzmová',
'Tibor Kollár',
'Anna Chamajová',
'Miroslav Tomčo',
'Eva Turbáková',
'Peter Smrčo',
'Jaroslav Mlynek',
'Anna Ohradzanská',
'Juraj Cinkanič',
'Veronika Paraska',
'Jozef Líška',
'Peter Galanský',
'Igor Čombor',
'Roman Malánik',
'Henrich Ravas',
'Daniela Trňanová',
'Ľubomír Eremiáš',
'Eva Nemčovská',
'Michal Repaský',
'Peter Barát',
'Ivan Sádecký',
'Iveta Tomková',
'Silvia Cagalová',
'Ľubomír Lőrincz',
'František Miklós',
'Marta Bystránová',
'Iveta Hladká',
'Jana Ešmírová',
'Zoltán Srna',
'Ján Škamla',
'Dana Kolláriková',
'Martin Schvarc',
'Anton Vrecko',
'Jozef Deák',
'Jozef Gamrát',
'Michal Urban',
'Ladislav Tomáň',
'Marek Guman',
'Matej Sabol',
'Pavol Tichý',
'Peter Tokár',
'Adrian Krajčír',
'Pavel Celeng',
'Ján Kupec',
'Vladimír Bodnár',
'Mária Šulcová',
'Stanislav Svatik',
'Igor Mandák',
'Milan Mikulec',
'Marcela Gallová',
'Dušan Badinský',
'Jozef Pončák',
'Martin Džačovský',
'Ján Ragač',
'Peter Saboslai',
'Oľga Bartková',
'Martin Tomčányi',
'Anna Gavajdová',
'Ľubomír Piták',
'Marián Ilčík',
'Július Maďar',
'Katarína Grófová',
'Róbert Repka',
'Tomáš Várady',
'Alžbeta Sanislóová',
'Bartolomej Angyal',
'Daniel Fakla',
'Viktor Kalán',
'Juraj Kližan',
'Anna Mierna',
'Jozef Cech',
'Anton Horečný',
'Ľubomír Vranka',
'Alena Kalinová',
'Marta Kálovcová',
'Anna Silvestrová',
'Božena Drobková',
'Erika Lahutová',
'Ľubomír Meliš',
'Ján Mičko',
'Tomáš Kolembus',
'Anton Szabó',
'Ján Bačo',
'Jozef Bela',
'Martina Urbanová',
'Milan Diheneščík',
'Daniel Gelien',
'Árpád Bazsó',
'Alena Vranková',
'Zuzana Koláriková',
'Darina Hroncová',
'Vladislav Vrábeľ',
'Gejza Ambrúš',
'Iveta Pavliková',
'Anna Prekopová',
'Ján Jakubovský',
'Štefan Bašták',
'Jozef Magát',
'Ján Határ',
'Ľubica Balgová',
'Kamil Minda',
'Ján Michalko',
'Marcela Sekrénešová',
'Štefan Hrenák',
'Marek Straka',
'Lenka Hierzer Štiber',
'Roland Lamper',
'Andrej Kusý',
'Stanislav Gallik',
'Pavol Šimurda',
'Denisa Árvayová',
'Anna Mužíková',
'Marek Balica',
'Ján Kalinič',
'Štefan Gašparovič',
'Gabriela Kopnická',
'Vladimír Baran',
'Miroslava Szitová',
'Anton Chrvala',
'Vladimír Smolinský',
'Marián Pohly',
'Radoslav Dlugoš',
'Ingrid Tripšanská',
'Ladislav Hološ',
'Ján Bijalko',
'Milan Hlavatý',
'Daniela Galandová',
'Marian Hudec',
'Ivana Ivančová',
'Dušan Horňák',
'Pavol Džurina',
'Iveta Krupcová',
'Ľuboš Šuca',
'František Beregszászi',
'František Mayer',
'Marián Dóczy',
'Jozef Berta',
'Juraj Soboňa',
'Juraj Krištof',
'Mária Sajková',
'Radoslav Slivka',
'Anna Čermáková',
'Ján Juhász',
'Mária Bučková',
'Jozef Kuna',
'Pavol Bečarik',
'Ján Kurňava',
'Radoslav Šeliga',
'Marián Luha',
'Jozef Dudžák',
'Michal Kapusta',
'Zuzana Nebusová',
'Ľubomír Fifik',
'Vladimír Ledecký',
'Adriana Tkáčová',
'Mária Kleinová',
'Ján Greš',
'Miroslav Bober',
'Ján Stošek',
'Ján Hančin',
'Vladimír Urban',
'Ján Krucovčin',
'Ildikó Lászlóová',
'Ján Podmanický',
'Jozef Gembec',
'Milan Gonda',
'Stanislav Rigo',
'Peter Michalka',
'Ľubomír Lauf',
'Ľuboš Tomko',
'Pavol Kováč',
'Leopold Barszcz',
'Ján Jarábek',
'Michal Bereznanin',
'Marián Gajdoš',
'Jana Kolejová',
'Helena Szabóová',
'Peter Štefan',
'Ladislav Šimčisko',
'Peter Gojdič',
'Gabriel Šiba',
'Slavomír Mlynár',
'Darina Petrincová',
'Viera Kravčáková',
'Jozef Papán',
'Rastislav Sloveňák',
'Martin Šmíro',
'Jaroslav Mitaš',
'Daša Ovšonková',
'Ján Poliak',
'Július Horváth',
'Vladimír Dunajčák',
'Dušan Štadáni',
'Zoltán Mento',
'Štefan Benko',
'Ján Téglás',
'Ján Majer',
'Roman Hudy',
'Matej Šarocký',
'Juraj Hrišo',
'Iveta Ihnatková',
'Tibor Sluťak',
'Ondrej Brendza',
'Eva Magová',
'Jozef Rusnák',
'Boris Soukup',
'Hedviga Billá',
'Peter Novisedlák',
'Peter Krajčoviech',
'Martin Rybár',
'Daniela Šinková',
'Andrea Hanuliaková',
'Katarína Petrenčáková',
'Miloš Šustek',
'Martin Glončák',
'Anna Triznová',
'Jarmila Lopatová',
'Eva Cinkotová',
'Jozef Temer',
'Alena Jedináková',
'Anna Hiľáková',
'Jaroslav Bušfy',
'Gabriel Svorad',
'Štefan Vaclavik',
'Gabriel Lakatoš',
'Alžbeta Mátyásová',
'Ivan Lobodáš',
'Michal Širochman',
'Gustáv Liszkai',
'Martin Kminiak',
'Šimon Gabura',
'Dušan Matejka',
'Jozef Jobbágy',
'Roman Lisický',
'Maroš Ondráš',
'Pavol Ceľuch',
'Martina Husárová',
'Anna Paňková',
'Marcela Ivančová',
'Miroslav Nawrat',
'Ľubomír Šimko',
'Magdaléna Kondásová',
'Anna Sýkorová',
'Dáša Vojsovičová',
'Szabolcs Méri',
'Vladimír Hromádka',
'Renáta Majchráková',
'Štefan Gregor',
'Pavol Burda',
'Jozef Belický',
'Helena Mesárošová',
'Tibor Púček',
'Renáta Kassaiová',
'Štefan Petrus',
'Csaba Orosz',
'Emil Ircha',
'Jaroslav Mikula',
'Stanislav Skasko',
'Ján Hudák',
'Jaroslav Fogaš',
'Peter Merkovský',
'Andrej Buvalič',
'Marko Angelovič',
'Ľubomír Rešetár',
'Jozef Mačo',
'Anton Durkáč',
'Michal Kimák',
'Beata Székelyová',
'Magdaléna Jónášová',
'Jozef Vargovčík',
'Jaroslav Suchánek',
'Július Ferencz',
'Ružena Opálková',
'Ján Marchevský',
'Martin Köver',
'Peter Fitz',
'Peter Badinka',
'Peter Lenárt',
'Arnold Kurunci',
'Štefan Gál',
'František Sedlák',
'Stanislava Režnáková',
'Eduard Hollý',
'Janka Miškufová',
'Tibor Dímik',
'Nándor Kisfaludi',
'Stanislav  Bartoš',
'Elena Valachová',
'Ľudovít Sendrei',
'Michal Pidanič',
'Marian Janiš',
'Adrián Macho',
'Július Zemko',
'Martina Wilhelmerová',
'Vladimír Bien',
'Anna Šušoliaková',
'František Chudý',
'Ivan Maťuga',
'Viliam Tekula',
'František Kolarčík',
'Slavomír Bujko',
'Gabriela Arpášová',
'Jana Rišková',
'Štefan Madunický',
'Stanislav Neuschl',
'Ladislav Zvara',
'Štefan Vároš',
'Zuzana Vinkovičová',
'Ladislav Belányi',
'Anton Imling',
'Martin Hajko',
'Michal  Sýkora ',
'Norbert Keszi',
'Eugen Szabó',
'Pavol Habdák',
'Péter Őry',
'Michal Pastorek',
'Marianna Marková',
'Jarmila Gordanová',
'Stanislav Kubaský',
'Marek Oremus',
'Marek Peňaško',
'Zoltán Végh',
'Žaneta Gogolová',
'Miroslav Rajčo',
'Ľubomír Maďari',
'Ján Mlynár',
'Vladimír Končík',
'Milan Široň',
'Július Molnár',
'Gabriela Šplehová',
'Janette Cimermanová',
'Pavol Bugaj',
'Anna Kuľková',
'Milan Hrešo',
'Alena Pitoňáková',
'Tibor Taldík',
'Alena Rolincová',
'Jozef Dolinaj',
'Marián Kotora',
'Erika Valkovičová',
'Vojtech Ožvald',
'Peter Novysedlák',
'Róbert Szurdi',
'Oľga Fakanová',
'Peter Lačný',
'Viliam Mrázik',
'Michal Kolena',
'Janka Janšová',
'Iveta Gajdošová',
'Jozef Dávidík',
'Miroslav Angelovič',
'Juraj Senderák',
'Daniel Bago',
'Štefan Valkovič',
'Ildikó Kőrösi',
'Marián Čuhanič',
'Ľubica Džugánová',
'Juraj Krajčík',
'Jozef Kačmár',
'Irena Milecová',
'Miroslav Kupči',
'Jana Ivaničová',
'Jana Medvecová',
'Zoltán Horváth',
'István  Pomichal',
'Ján Mičuda',
'Vojtech Gyurán',
'Mária Bobriková',
'Alexandra Gieciová',
'Juraj Mesko',
'Zoltán Szilvási',
'László Bacsó',
'Štefan Ladičkovský',
'Gustáv Pompa',
'Anna Szögedi',
'Jozef Stedina',
'Ján Čarák',
'Kvetoslava Mižáková',
'Marián Kerčák',
'Alena Ščibrányiová',
'Imrich Bugár',
'Ľudovít Tolarovič',
'Emil Ivan',
'Karol Farkas',
'Juraj Valo',
'Štefánia Cibuľáková',
'Marcel Hudec',
'Iveta Šebeňová',
'Marek Čižmár',
'Ivan Trimaj',
'Marek Krnáč',
'Andrej Barcík',
'Slavomíra Propperová',
'Peter Mikula',
'Darina Jurigová',
'Marek Brožek',
'Jana Šebáňová',
'Martin Markech',
'Zuzana Frajková Ďurmeková',
'Richard Rybníček',
'Gergely Török',
'Róbert Koba',
'Peter Bročka',
'Pavel Kravec',
'Vladimír Adam',
'Attila Horváth',
'Božena Filková',
'Martina Kubincová',
'Jiří Ballarin',
'Jozef Kotvan',
'Oliver Berecz',
'Martin Buocik',
'Matúš Stavar',
'Miroslav Melaga',
'Rudolf Pupala',
'Magdaléna Zmarzláková',
'Zuzana Bónová',
'Anna Naďová',
'Matej Kočiš',
'Eva Kaczová',
'Peter Hlávek',
'Peter Čeman',
'František Lorinc',
'Rastislav Krajčík',
'Danka Dobranská',
'Erika Holomeková',
'Margaréta Bogárová',
'Dušan Novysedlák',
'Cyril Vasiľ',
'Ján Teltsch',
'Eva Dragulová',
'Peter Očka',
'Rastislav Jesenský',
'Adriana Záborská',
'Igor Hus',
'Viera Hanesová',
'Ondrej Výbošťok',
'Tatiana Belánová',
'Ivan Janovec',
'Štefan Čermák',
'Alica Kostolná',
'Vladimír Hatiar',
'Atila Oravecz',
'János Koleszár',
'Jana Jarotová',
'Ľubomír Golis',
'Ján Záhorský',
'Jarmila Vaľovská',
'Miroslav Dzina',
'Dagmar Mathiová',
'Jozef Beňo',
'Ivan Šaško',
'Marián Tóth',
'Nadežda Sirková',
'Martin Hvižďak',
'Peter Hudák',
'Peter Chochlík',
'Vladimír Kravec',
'Ferdinand Ďurdík',
'Roman König',
'Vladimír Multáň',
'Pavel Olšiak',
'Zuzana Máčeková',
'Javier Linde Esteban',
'Rudolf Frýželka',
'Ján Holinka',
'Juraj Cogan',
'Pavol Abrahamovský',
'Lenka Sedmáková',
'Ján Palkovič',
'Matúš Hubinský',
'Miroslav Barutiak',
'Jaroslav Golodžej',
'Peter Babík',
'Marek Gruška',
'Jozef Merva',
'Alžbeta Tuková',
'Peter Klim',
'Adrián Kubica',
'Róbert Čorba',
'Štefan Petrík',
'Peter Jenča',
'Miloš Cúcik',
'Igor Tulinský',
'Mária Ondráčková',
'Michal Firkaľ',
'Ján Ďuriška',
'Ján Chrzan',
'Mária Bobáková',
'Marcel Kvokačka',
'Jaroslav Krajkovič',
'Sylvia Chudíková',
'Milan Hudák',
'Ľubica Pankievičová',
'Michal Cvacho',
'Anton Grigeľ',
'Peter Kružel',
'Helena Kiššová',
'Ľubica Chlebová',
'Milan Lištiak',
'Ľubomír Kosztúr',
'Tibor Kovács',
'Ladislav Tóth',
'Mikuláš Levkut',
'Ľubomír Gahír',
'Daniel Laura',
'Roman Pásztor',
'Nikola Pekárová',
'Ján Matejička',
'Vladimír Tulipán',
'Pavol  Soľava',
'Anna Petríková',
'Peter Nagy',
'Jozef Mihál',
'Ján Michna',
'Ján Lukáč',
'Peter Duda',
'Andrea Chromeková',
'Štefan Lancz',
'Gabriel Rácz',
'Ivan Seňan ml.',
'Helena Kavčáková',
'Jozef Líška',
'Ladislav Kerata',
'Silvia Masárová',
'Júlia Gányovicsová',
'Kamil Jančura',
'Viera Rubintová',
'Marián Čerňanský',
'Ladislav Jančovič',
'Ján Ürögi',
'Gabriela Bronišová',
'Zuzana Flórová',
'Csaba Farkas',
'Peter Petrikán',
'Lajos Csóka',
'Gilbert Liška',
'Tomáš Báťa',
'Vladimír Kopál',
'Richard Nimsch',
'Libor Kráľ',
'Zita Cseri',
'Pavol Paulovič',
'Alena Kováčová',
'František Demeter',
'Elemér Jakab',
'Martin Hrunka',
'Jozef Krištof',
'Jozef Mičieta',
'Ľudovít Tóth',
'Ján Jakab',
'Kamil Kučera',
'József Kopasz',
'Jaroslav Péter',
'Alena Chalupová',
'František Gőgh',
'Justína Pálková',
'Milan Bíro',
'Ivan Krahulec',
'Marián Prokopič',
'Anton Danter',
'Norbert Kluka',
'František Mészáros',
'Jana Boďová',
'Peter Benko',
'Milan Grega',
'Viliam Rigo',
'Zoltán Pál',
'Attila Nagy',
'Anton Stanko',
'Dalibor Surkoš',
'Judita Valašková',
'Katarína Babalová',
'Peter Labant',
'Michal Minár',
'Gergő Holényi',
'Slavomír Pucci',
'Jana Sabolová',
'Viliam Kall',
'Valéria Klapáčová',
'Rastislav Zemánik',
'Vladimír Ondruš',
'Viera Šipková',
'Desana Stromková',
'Ján Šupica',
'Robert Mocsonoky',
'Anna Makovníková',
'Július Bodon',
'Štefan Mladý',
'Róbert Záchenský',
'Jozef Tuček',
'Vladimír Šavel',
'Kristián Baksa',
'Michal Takáč',
'Pavel Galamboš',
'Marián Makeľ',
'Peter Straňák',
'Eva Hanusová',
'Ivana Juráčková',
'Ladislav Lengyel',
'Michal Struk',
'Milan Haňak',
'Vincenc Hrenák',
'Marta Pejová',
'Pavol Hluchý',
'Marcela Halaganová',
'Zoltán Borsodi',
'Mária Vráblová',
'Dušan Ondrík',
'Ján Baloga',
'Veronika Pošiková',
'Peter Dirda',
'Michal Kľučár',
'Ján Čurpek',
'Peter Pakes',
'Róbert Klubica',
'János Restár',
'Ivan Dobrovodský',
'Antonín Melichar',
'Martina Horváthová',
'Peter Bendík',
'Ján Kalata',
'Baltazár Fejes',
'Gejza Ujj',
'Anita Gajarská',
'Štefan Czinke',
'Vlastimil Kiral-Varga',
'Zsolt Kulcsár',
'Donald Álló',
'Rastislav Kolej',
'Marián Gaborčík',
'Silvia Ihnatová',
'Helena Kasardová',
'Štefan Gajdoš',
'Monika Rohaľová',
'Ondrej Kozolka',
'Kamil Blaho',
'Tamás Zupko',
'Jaroslav Bazala',
'Tibor Tóth',
'Milan Kováč',
'Štefan Fazekas',
'Ján Ragan',
'Jaroslav Tokár',
'Tatiana Faltinová',
'Peter Ilčík',
'Dušan Eliáš',
'Ema Maggiová',
'Marcel Fagyas',
'Ladislav Kolek',
'František Hideg',
'Peter Remiš',
'Branislav Zacharides',
'Gabriela Gáborová',
'Viera Strelová',
'Jozef Holúbek',
'Ladislav Balódi',
'Milan Gášek',
'Jozef Bizoň',
'Ervín Családi',
'Pavel Krupa',
'Monika Kurťaková',
'Ivan Sečanský',
'Valéria Kuková',
'Lucia Hurajtová',
'Anton Varecha',
'Ján Hrešan',
'Dušan Dvoran',
'Ján Mokoš',
'Dušan Antoš',
'Ágnes Antal Nyustin',
'Ľubica Trégerová',
'Agáta Nosáľová',
'Zuzana Nestorová',
'Miroslav Čepan',
'Ján Mikloš',
'Marek Habina',
'Juraj Kasarda',
'Vasil Pitlivka',
'Ľuboš Špik',
'František Gejguš',
'Viktor Kušnír',
'Dušan Gallo',
'Marián Beluško',
'Ján Evin',
'Martina Bobaľová',
'Eva Madarásová',
'Peter Zuza',
'Martin Dolinič',
'Jozef Gura',
'Peter Martinek',
'Ján Záhorský',
'Vincent Borovský',
'Monika Sipľaková',
'Milan Naster',
'Michal Duda',
'Ondrej Jusko',
'Daniela Štefancová',
'Emília Novotná',
'Antonín Zámečník',
'Róbert Nálepka',
'Michal Petranik',
'Ján Džupin',
'Ján Durmis',
'Gabriela Grobarčíková',
'Jozef Balaščák',
'Miroslav Ondič',
'Ján Banovčan',
'Ján Záborský',
'Kristína Maliňáková',
'Július Nehoda',
'Ildikó Kovács',
'Marián Hric',
'Branislav Kázmer',
'Boris Šimkovič',
'Róbert Tkáč',
'Ružena Gembická',
'Peter Klimčík',
'Ján Slaninák',
'Melinda Bögi Pathó',
'Marián  Perger',
'Martin Klimek',
'Gabriel Viňanský',
'Peter Minárik',
'Stanislav Duda',
'Jozef Kollár',
'František Koleno',
'Mikuláš Kukó',
'Ján Bajzík',
'Miroslav Kalmár',
'Miluška Hlavatá',
'Renáta Bešáková',
'Jana Dziaková',
'Vladimír Kišák',
'Ján Tešlár',
'Lukáš Sochor',
'Pavel Beťko',
'Peter Vrablec',
'Matúš Mních',
'Ján Ferko',
'Adam Žákovič',
'Ladislav Ladomirjak',
'Anna Koščová',
'Ján Šurkala',
'Juraj Hlavatý',
'Emőke Fillová',
'Milan Matúška',
'František Kopej',
'Matej Havrila',
'Marián Miškovský',
'Ľubomír Jedlička',
'Dezső Magyarics',
'Jana Školíková',
'Miroslav Zámečník',
'Roman Súkeník',
'Jana Horečná Budinská',
'János Bób',
'Mikuláš Takács',
'Kamil Bodnár',
'Vladimír Mati',
'Jozefína Uhaľová',
'Ján Kepič',
'Ján Oláh',
'Miroslav Maďar',
'Ladislav Kohut',
'Jozef Tóth',
'Maroš Železník',
'Roman Beličák',
'Adriana Popjaková',
'Marek Rigó',
'Dušan Husár',
'Eva Varjúová',
'Juraj Balog',
'Erik Števula',
'Martin Zeman',
'Margaréta Murínová',
'Anton Miko',
'Martin Zálesňák',
'Marián Galo',
'Pavol Gelo',
'Vladimír Šiška',
'Michaela Vasilenková',
'Pavol Bugeľ',
'Lenka Balkovičová',
'Mária Klimentová',
'Katarína Dudášová',
'Zuzana Valocká',
'Cyril Cabadaj',
'Štefan Tulipán',
'Katarína Krullová',
'Valéria Račková',
'Ján Kulcsár',
'Kamil Danko',
'Milan Pavlovčík',
'Ján Jurko',
'Ján Kokarda',
'Pavel Bekeš',
'Atila Géňa',
'Marián Kandráč',
'Ján Dúbravský',
'Andrej Mitaľ',
'Ondrej Juhász',
'Anna Stašková',
'Štefan Rimaj',
'Slavomír Bárczy',
'Andrea Gubíková',
'Ján Zvara',
'Zoltán Csizmadia',
'Peter Antal',
'Dušan Laco',
'Alajos Baranyay',
'Jozef Broniš',
'Peter Fiabáne',
'Béla Simon',
'Jozef Štofanko',
'Jozef Zsebi',
'Edita Grzybová',
'Stanislav Strieška',
'Rudolf Botka',
'Jozef Daniška',
'František Novotný',
'Ján Tomáš',

    ]
     




    export {obce, starostovia}